extends: plumber:default
version: "2.0"

github:
  controls:
    branchMustBeProtected:
      codeOwnerApprovalRequired: true
    githubActionMustComeFromAuthorizedSources:
      minimumStars: 0
      trustedGithubActions:
        - getplumber/plumber
        - anthropics/claude-code-action
        - docker/setup-qemu-action
        - docker/setup-buildx-action
        - docker/login-action
        - docker/metadata-action
        - docker/build-push-action
        - ossf/scorecard-action
        - anchore/scan-action
        - DavidAnson/markdownlint-cli2-action
        - ruby/setup-ruby
        - gitleaks/gitleaks-action
        - golangci/golangci-lint-action
        - aquasecurity/trivy-action
