//go:build linux

package integration

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"syswarden-cli/pkg/system"

	"golang.org/x/sys/unix"
)

const (
	rsyslogAppArmorDirectory = "apparmor.d"
	rsyslogAppArmorProfile   = "usr.sbin.rsyslogd"
	rsyslogAppArmorSnippet   = "syswarden"
	trustedAppArmorParser    = "/usr/sbin/apparmor_parser"
	rsyslogAppArmorPolicy    = "# Generated by SysWarden. Permit only the local logging socket.\n/run/syswarden.sock w,\n"
)

var rsyslogAppArmorInclude = regexp.MustCompile(`(?m)^\s*#?include\s+(?:if\s+exists\s+)?<rsyslog\.d>\s*(?:#[^\n]*)?$`)
var rsyslogAppArmorHeader = regexp.MustCompile(`(?m)^\s*(?:profile\s+)?(rsyslogd\s+)?/usr/sbin/rsyslogd\s*(?:flags=\([^\n{}]*\)\s*)?\{\s*$`)

func rsyslogAppArmorProfileName(content []byte) (string, error) {
	headers := rsyslogAppArmorHeader.FindAllSubmatch(content, -1)
	if len(headers) != 1 || len(rsyslogAppArmorInclude.FindAll(content, -1)) != 1 {
		return "", fmt.Errorf("rsyslog AppArmor profile requires one recognized profile and one rsyslog.d include")
	}
	depth, profiles, includes := 0, 0, 0
	for _, raw := range strings.Split(string(content), "\n") {
		line := strings.TrimSpace(raw)
		if rsyslogAppArmorInclude.MatchString(line) {
			if depth != 1 || profiles != 1 {
				return "", fmt.Errorf("rsyslog.d include is outside the single rsyslog profile")
			}
			includes++
			continue
		}
		if depth == 0 && (strings.HasPrefix(line, "#include") || strings.HasPrefix(line, "include")) &&
			line != "#include <tunables/global>" && line != "include <tunables/global>" {
			return "", fmt.Errorf("unsupported include outside rsyslog AppArmor profile")
		}
		if rsyslogAppArmorHeader.MatchString(line) {
			if depth != 0 || profiles != 0 {
				return "", fmt.Errorf("multiple or nested rsyslog AppArmor profiles")
			}
			profiles++
		} else if depth == 0 && line != "" && !strings.HasPrefix(line, "#") &&
			line != "include <tunables/global>" && !strings.HasPrefix(line, "abi <abi/") {
			return "", fmt.Errorf("unsupported declaration outside rsyslog AppArmor profile")
		}
		if strings.HasPrefix(line, "#") {
			continue
		}
		if comment := strings.IndexByte(line, '#'); comment >= 0 {
			line = line[:comment]
		}
		depth += strings.Count(line, "{") - strings.Count(line, "}")
		if depth < 0 {
			return "", fmt.Errorf("unbalanced rsyslog AppArmor profile")
		}
	}
	if depth != 0 || profiles != 1 || includes != 1 {
		return "", fmt.Errorf("unsupported rsyslog AppArmor include scope")
	}
	if len(headers[0][1]) > 0 {
		return "rsyslogd", nil
	}
	return "/usr/sbin/rsyslogd", nil
}

type appArmorProfileSnapshot struct {
	directory *os.File
	identity  exactOwnedArtifactIdentity
	content   []byte
	name      string
}

// A vendor profile is trusted input, not a generated artifact. Reuse the
// bounded descriptor reader with its actual size, then retain its identity
// and bytes for every reload. Never rewrite a vendor or local override file.
func readRsyslogAppArmorProfile(directory *os.File, uid, gid uint32) (exactOwnedArtifactInspection, error) {
	var metadata unix.Stat_t
	if err := unix.Fstatat(int(directory.Fd()), rsyslogAppArmorProfile, &metadata, unix.AT_SYMLINK_NOFOLLOW); err != nil {
		return exactOwnedArtifactInspection{}, err
	}
	expectation := exactOwnedArtifactExpectation{
		label: "vendor rsyslog AppArmor profile", name: rsyslogAppArmorProfile,
		size: metadata.Size, permittedModes: map[uint32]struct{}{0600: {}, 0644: {}},
	}
	observed, err := inspectExactOwnedArtifact(directory, rsyslogAppArmorProfile, expectation, uid, gid)
	if err != nil || len(observed.content) == 0 {
		return observed, errors.Join(fmt.Errorf("refusing unreadable or unsafe rsyslog AppArmor profile: %s", observed.ambiguous), err)
	}
	return observed, nil
}

func captureRsyslogAppArmorProfile(parent string, uid, gid uint32) (*appArmorProfileSnapshot, error) {
	directory, exists, err := openExistingOwnedArtifactDirectoryAt(parent, rsyslogAppArmorDirectory, uid, gid)
	if err != nil || !exists {
		return nil, err
	}
	observed, err := readRsyslogAppArmorProfile(directory, uid, gid)
	if errors.Is(err, unix.ENOENT) {
		_ = directory.Close()
		return nil, nil
	}
	if err != nil {
		_ = directory.Close()
		return nil, err
	}
	name, err := rsyslogAppArmorProfileName(observed.content)
	if err != nil {
		_ = directory.Close()
		return nil, err
	}
	return &appArmorProfileSnapshot{directory: directory, identity: observed.identity, content: observed.content, name: name}, nil
}

func (profile *appArmorProfileSnapshot) attest(uid, gid uint32) error {
	current, err := readRsyslogAppArmorProfile(profile.directory, uid, gid)
	if err != nil || !sameOwnedArtifactIdentity(profile.identity, current.identity) || !bytes.Equal(profile.content, current.content) {
		return errors.Join(fmt.Errorf("vendor rsyslog AppArmor profile changed during reconciliation"), err)
	}
	return attestVisibleAppArmorDirectory(profile.directory)
}

func attestVisibleAppArmorDirectory(directory *os.File) error {
	visible, err := os.Lstat(directory.Name())
	opened, openedErr := directory.Stat()
	if err != nil || openedErr != nil || !os.SameFile(visible, opened) {
		return errors.Join(fmt.Errorf("AppArmor profile directory changed during reconciliation"), err, openedErr)
	}
	return nil
}

func readBoundedAppArmorKernelFile(path string) ([]byte, error) {
	var file *os.File
	var err error
	switch path {
	case "/sys/module/apparmor/parameters/enabled":
		file, err = os.Open("/sys/module/apparmor/parameters/enabled")
	case "/sys/kernel/security/apparmor/profiles":
		file, err = os.Open("/sys/kernel/security/apparmor/profiles")
	default:
		return nil, fmt.Errorf("unrecognized AppArmor kernel state path")
	}
	if err != nil {
		return nil, err
	}
	defer file.Close()
	wire, err := io.ReadAll(io.LimitReader(file, rsyslogArtifactContentLimit+1))
	if len(wire) > rsyslogArtifactContentLimit {
		return nil, fmt.Errorf("AppArmor kernel state exceeds its bound")
	}
	return wire, err
}

func rsyslogAppArmorMode(name string) (string, error) {
	return rsyslogAppArmorModeUsing(name, readBoundedAppArmorKernelFile)
}

func rsyslogAppArmorModeUsing(name string, read func(string) ([]byte, error)) (string, error) {
	enabled, err := read("/sys/module/apparmor/parameters/enabled")
	if errors.Is(err, os.ErrNotExist) || err == nil && strings.TrimSpace(string(enabled)) == "N" {
		return "unloaded", nil
	}
	if err != nil || strings.TrimSpace(string(enabled)) != "Y" {
		return "", errors.Join(fmt.Errorf("cannot establish AppArmor runtime state"), err)
	}
	wire, err := read("/sys/kernel/security/apparmor/profiles")
	if err != nil {
		return "", fmt.Errorf("read loaded AppArmor profiles: %w", err)
	}
	mode := "unloaded"
	for _, line := range strings.Split(string(wire), "\n") {
		if !strings.HasPrefix(line, name+" (") {
			continue
		}
		if mode != "unloaded" || line != name+" (enforce)" && line != name+" (complain)" {
			return "", fmt.Errorf("ambiguous rsyslog AppArmor runtime mode")
		}
		mode = strings.TrimSuffix(strings.TrimPrefix(line, name+" ("), ")")
	}
	return mode, nil
}

func reloadRsyslogAppArmorProfile(profile *appArmorProfileSnapshot, uid, gid uint32, mode string,
	inspectMode func(string) (string, error), run managedServiceRunner,
) error {
	if err := validateRsyslogAppArmorMode(profile, mode); err != nil {
		return err
	}
	if err := profile.attest(uid, gid); err != nil {
		return err
	}
	current, err := inspectMode(profile.name)
	if err != nil || current != mode {
		return errors.Join(fmt.Errorf("rsyslog AppArmor mode changed before reload"), err)
	}
	path := filepath.Join(profile.directory.Name(), rsyslogAppArmorProfile)
	args := []string{"--replace", "--skip-cache", "--skip-kernel-load", path}
	if output, err := run(trustedAppArmorParser, args...); err != nil {
		return fmt.Errorf("validate rsyslog AppArmor socket policy: %w: %s", err, output)
	}
	if mode != "unloaded" {
		current, err = inspectMode(profile.name)
		if err != nil || current != mode {
			return errors.Join(fmt.Errorf("rsyslog AppArmor mode changed during validation"), err)
		}
		args = []string{"--replace", "--skip-cache"}
		if mode == "complain" {
			args = append(args, "--Complain")
		}
		args = append(args, path)
		if output, err := run(trustedAppArmorParser, args...); err != nil {
			return fmt.Errorf("reload rsyslog AppArmor socket policy: %w: %s", err, output)
		}
	}
	current, err = inspectMode(profile.name)
	if err != nil || current != mode {
		return errors.Join(fmt.Errorf("rsyslog AppArmor mode changed after reload"), err)
	}
	return profile.attest(uid, gid)
}

func validateRsyslogAppArmorMode(profile *appArmorProfileSnapshot, mode string) error {
	if mode != "enforce" && mode != "complain" && mode != "unloaded" {
		return fmt.Errorf("unrecognized rsyslog AppArmor mode %q", mode)
	}
	if mode == "enforce" && bytes.Contains(rsyslogAppArmorHeader.Find(profile.content), []byte("complain")) {
		return fmt.Errorf("refusing an enforcing profile whose source requests complain mode")
	}
	return nil
}

func withRsyslogAppArmorSocketPolicy(action func() error) error {
	return withRsyslogAppArmorSocketPolicyAtUsing("/etc", 0, 0,
		rsyslogAppArmorMode, runManagedServiceCommand, requireRsyslogMutationWithoutRemovalBarrier, action)
}

func withRsyslogAppArmorSocketPolicyAtUsing(parent string, uid, gid uint32,
	inspectMode func(string) (string, error), run managedServiceRunner, barrier, action func() error,
) error {
	if inspectMode == nil || run == nil || barrier == nil || action == nil {
		return fmt.Errorf("AppArmor socket policy controls are unavailable")
	}
	profile, err := captureRsyslogAppArmorProfile(parent, uid, gid)
	if err != nil {
		return err
	}
	if profile == nil {
		if err := attestRsyslogAppArmorSocketPolicyAbsent(parent, uid, gid); err != nil {
			return err
		}
		return action()
	}
	defer profile.directory.Close()
	mode, err := inspectMode(profile.name)
	if err != nil {
		return err
	}
	if err := validateRsyslogAppArmorMode(profile, mode); err != nil {
		return err
	}
	directory, err := openWAFRsyslogDirectoryAt(filepath.Join(parent, rsyslogAppArmorDirectory), uid, gid)
	if err != nil {
		return err
	}
	defer directory.Close()
	if err := unix.Flock(int(directory.Fd()), unix.LOCK_EX); err != nil {
		return err
	}
	defer func() { _ = unix.Flock(int(directory.Fd()), unix.LOCK_UN) }()
	expectation := exactContentExpectation("rsyslog AppArmor socket policy", rsyslogAppArmorSnippet, []byte(rsyslogAppArmorPolicy), 0600)
	initial, err := inspectExactOwnedArtifact(directory, rsyslogAppArmorSnippet, expectation, uid, gid)
	if err != nil || initial.identity.exists && !initial.exact {
		return errors.Join(fmt.Errorf("preserving unrecognized rsyslog AppArmor socket policy: %s", initial.ambiguous), err)
	}
	if err := requireOwnedArtifactAbsent(directory, exactArtifactQuarantineName(rsyslogAppArmorSnippet), "AppArmor removal transaction"); err != nil {
		return err
	}
	beforePublication := func() error {
		if err := barrier(); err != nil {
			return err
		}
		current, err := inspectExactOwnedArtifact(directory, rsyslogAppArmorSnippet, expectation, uid, gid)
		if err != nil || !sameOwnedArtifactIdentity(initial.identity, current.identity) {
			return errors.Join(fmt.Errorf("AppArmor socket policy changed before publication"), err)
		}
		if err := attestVisibleAppArmorDirectory(directory); err != nil {
			return err
		}
		return profile.attest(uid, gid)
	}
	if err := beforePublication(); err != nil {
		return err
	}
	// Discover missing tools or an invalid pre-existing profile before any
	// publication. This validation cannot load or enable a kernel profile.
	if output, err := run(trustedAppArmorParser, "--replace", "--skip-cache", "--skip-kernel-load",
		filepath.Join(profile.directory.Name(), rsyslogAppArmorProfile)); err != nil {
		return fmt.Errorf("validate existing rsyslog AppArmor profile before publication: %w: %s", err, output)
	}
	reload := func() error {
		if err := attestVisibleAppArmorDirectory(directory); err != nil {
			return err
		}
		return reloadRsyslogAppArmorProfile(profile, uid, gid, mode, inspectMode, run)
	}
	rollback := func() error {
		if initial.identity.exists {
			return nil
		}
		options := defaultExactOwnedArtifactRemovalOptions()
		options.beforeCommit, options.afterRestore = reload, reload
		_, err := removeExactOwnedArtifactInDirectoryUsing(directory, uid, gid, expectation, options)
		return err
	}
	_, err = reconcileRsyslogArtifactInDirectoryUsing(directory, rsyslogAppArmorSnippet, uid, gid,
		[]byte(rsyslogAppArmorPolicy), beforePublication, func(directory *os.File) error { return directory.Sync() })
	if err != nil {
		return errors.Join(err, rollback())
	}
	if err := reload(); err != nil {
		return errors.Join(err, rollback())
	}
	if err := action(); err != nil {
		return errors.Join(err, rollback())
	}
	return nil
}

func removeRsyslogAppArmorSocketPolicyForPackageRemoval() error {
	if err := system.RequireRemovalTombstone(); err != nil {
		return err
	}
	return removeRsyslogAppArmorSocketPolicyAtUsing("/etc", 0, 0, rsyslogAppArmorMode, runManagedServiceCommand)
}

func removeRsyslogAppArmorSocketPolicyAtUsing(parent string, uid, gid uint32,
	inspectMode func(string) (string, error), run managedServiceRunner,
) error {
	if inspectMode == nil || run == nil {
		return fmt.Errorf("AppArmor socket policy removal controls are unavailable")
	}
	directory, exists, err := openExistingOwnedArtifactDirectoryAt(filepath.Join(parent, rsyslogAppArmorDirectory), wafRsyslogDirectoryName, uid, gid)
	if err != nil || !exists {
		return err
	}
	defer directory.Close()
	if err := unix.Flock(int(directory.Fd()), unix.LOCK_EX); err != nil {
		return err
	}
	defer func() { _ = unix.Flock(int(directory.Fd()), unix.LOCK_UN) }()
	if err := attestRsyslogAppArmorTargetsAbsent(directory); err == nil {
		return nil
	}
	profile, err := captureRsyslogAppArmorProfile(parent, uid, gid)
	if err != nil || profile == nil {
		return errors.Join(fmt.Errorf("cannot remove AppArmor socket policy without its vendor profile"), err)
	}
	defer profile.directory.Close()
	mode, err := inspectMode(profile.name)
	if err != nil {
		return err
	}
	options := defaultExactOwnedArtifactRemovalOptions()
	reload := func() error {
		if err := attestVisibleAppArmorDirectory(directory); err != nil {
			return err
		}
		return reloadRsyslogAppArmorProfile(profile, uid, gid, mode, inspectMode, run)
	}
	options.beforeCommit, options.afterRestore = reload, reload
	expectation := exactContentExpectation("rsyslog AppArmor socket policy", rsyslogAppArmorSnippet, []byte(rsyslogAppArmorPolicy), 0600)
	if _, err := removeExactOwnedArtifactInDirectoryUsing(directory, uid, gid, expectation, options); err != nil {
		return err
	}
	return attestRsyslogAppArmorTargetsAbsent(directory)
}

func attestRsyslogAppArmorTargetsAbsent(directory *os.File) error {
	if _, err := directory.Seek(0, io.SeekStart); err != nil {
		return err
	}
	entries, err := directory.Readdirnames(-1)
	if err != nil {
		return err
	}
	for _, name := range entries {
		if name == rsyslogAppArmorSnippet || name == exactArtifactQuarantineName(rsyslogAppArmorSnippet) ||
			name == "."+rsyslogAppArmorSnippet+exactArtifactRecreationSuffix ||
			strings.HasPrefix(name, "."+rsyslogAppArmorSnippet+".syswarden-") && strings.HasSuffix(name, ".tmp") {
			return fmt.Errorf("rsyslog AppArmor teardown target %q remains", name)
		}
	}
	return nil
}

func attestRsyslogAppArmorSocketPolicyAbsent(parent string, uid, gid uint32) error {
	directory, exists, err := openExistingOwnedArtifactDirectoryAt(filepath.Join(parent, rsyslogAppArmorDirectory), wafRsyslogDirectoryName, uid, gid)
	if err != nil || !exists {
		return err
	}
	defer directory.Close()
	if err := unix.Flock(int(directory.Fd()), unix.LOCK_SH); err != nil {
		return err
	}
	defer func() { _ = unix.Flock(int(directory.Fd()), unix.LOCK_UN) }()
	return attestRsyslogAppArmorTargetsAbsent(directory)
}
