//go:build linux

package integration

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Frozen v4.02.8 generator bytes are removal evidence only. Never publish or
// activate this historical bridge. Its glob is deliberately not expanded:
// absent or rotated log files do not change the originally generated bytes.
const historicalV4028WAFBase = `module(load="imfile")
module(load="omuxsock")
$OMUxSockSocket /var/run/syswarden.sock

# Web Server Logs
input(type="imfile" File="/var/log/nginx/*.log" Tag="syswarden-waf" ruleset="waf_bridge")
input(type="imfile" File="/var/log/apache2/*.log" Tag="syswarden-waf" ruleset="waf_bridge")
input(type="imfile" File="/var/log/httpd/*.log" Tag="syswarden-waf" ruleset="waf_bridge")

# System & Auth Logs (HIDS)
input(type="imfile" File="/var/log/auth.log" Tag="syswarden-waf" ruleset="waf_bridge")
input(type="imfile" File="/var/log/secure" Tag="syswarden-waf" ruleset="waf_bridge")
input(type="imfile" File="/var/log/syslog" Tag="syswarden-waf" ruleset="waf_bridge")
input(type="imfile" File="/var/log/messages" Tag="syswarden-waf" ruleset="waf_bridge")
`

const historicalV4028WAFRuleset = `
template(name="SYSWARDENRaw" type="string" string="%msg%\n")

ruleset(name="waf_bridge") {
    # Prevent infinite loops from SYSWARDEN logging its own blocks
    if $programname == "syswarden-core" then stop
    if $msg contains "SYSWARDEN-BLOCK" then stop
    if $msg contains "SYSWARDEN-ALLOWED" then stop

    # Do not forward native firewall kernel drops to WAF regex engine to avoid false positives and reduce CPU overhead
    if $msg contains "SYSWARDEN-GEO" then stop
    if $msg contains "SYSWARDEN-ASN" then stop
    if $msg contains "SYSWARDEN-L3" then stop
    if $msg contains "SYSWARDEN-TOR" then stop
    if $msg contains "SYSWARDEN-PROXY" then stop

    *.* :omuxsock:;SYSWARDENRaw
}
`

func renderHistoricalV4028WAFForRemoval(rawPatterns string) (string, error) {
	custom := ""
	if rawPatterns != "" {
		quoted, err := quoteRsyslogString(rawPatterns)
		if err != nil || quoted != "\""+rawPatterns+"\"" {
			return "", fmt.Errorf("historical WAF log pattern is not an exact unescaped string")
		}
		patterns := strings.Fields(rawPatterns)
		if len(patterns) == 0 || strings.Join(patterns, " ") != rawPatterns {
			return "", fmt.Errorf("historical WAF log patterns are not canonical")
		}
		seen := make(map[string]bool, len(patterns))
		for _, pattern := range patterns {
			if !filepath.IsAbs(pattern) || filepath.Clean(pattern) != pattern || seen[pattern] {
				return "", fmt.Errorf("historical WAF log pattern is not an exact absolute path")
			}
			if _, err := filepath.Match(pattern, pattern); err != nil {
				return "", fmt.Errorf("historical WAF log glob is invalid: %w", err)
			}
			seen[pattern] = true
		}
		custom = fmt.Sprintf("\n# Docker Multi-Tenant Logs\ninput(type=\"imfile\" File=\"%s\" Tag=\"syswarden-waf\" ruleset=\"waf_bridge\")\n", rawPatterns)
	}
	return historicalV4028WAFBase + custom + historicalV4028WAFRuleset, nil
}
