//go:build linux

package integration

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"syswarden-cli/config"
	"syswarden-cli/pkg/security"
	"testing"

	"golang.org/x/sys/unix"
)

func newOwnedArtifactRemovalFixture(t *testing.T) (string, string, uint32, uint32) {
	t.Helper()
	parent := t.TempDir()
	directoryName := "managed.d"
	directory := filepath.Join(parent, directoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatalf("create managed fixture directory: %v", err)
	}
	info, err := os.Stat(parent)
	if err != nil {
		t.Fatalf("stat managed fixture parent: %v", err)
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		t.Fatal("managed fixture parent has no Linux stat metadata")
	}
	return parent, directoryName, stat.Uid, stat.Gid
}

func writeOwnedArtifactFixture(t *testing.T, path string, content []byte, mode os.FileMode) {
	t.Helper()
	if err := os.WriteFile(path, content, mode); err != nil {
		t.Fatalf("write managed artifact fixture: %v", err)
	}
	if err := os.Chmod(path, mode); err != nil {
		t.Fatalf("set managed artifact fixture mode: %v", err)
	}
}

func quietOwnedArtifactRemovalOptions(warnings *[]string) exactOwnedArtifactRemovalOptions {
	options := defaultExactOwnedArtifactRemovalOptions()
	options.warn = func(message string) {
		*warnings = append(*warnings, message)
	}
	return options
}

func TestExactOwnedArtifactRemovalQuarantinesReattestsAndUnlinks_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	content := []byte("exact generated bytes\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	path := filepath.Join(parent, directoryName, expectation.name)
	writeOwnedArtifactFixture(t, path, content, 0600)

	warnings := []string{}
	options := quietOwnedArtifactRemovalOptions(&warnings)
	syncCalls := 0
	originalSync := options.syncDirectory
	options.syncDirectory = func(directory *os.File) error {
		syncCalls++
		return originalSync(directory)
	}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent,
		directoryName,
		uid,
		gid,
		expectation,
		options,
	)
	if err != nil || !removed {
		t.Fatalf("exact removal = %t, %v", removed, err)
	}
	if len(warnings) != 0 {
		t.Fatalf("exact removal warnings = %v", warnings)
	}
	if syncCalls != 2 {
		t.Fatalf("directory sync calls = %d, want rename and unlink durability", syncCalls)
	}
	if _, err := os.Lstat(path); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("exact artifact remains: %v", err)
	}
	entries, err := os.ReadDir(filepath.Dir(path))
	if err != nil {
		t.Fatalf("read managed directory after removal: %v", err)
	}
	for _, entry := range entries {
		if strings.Contains(entry.Name(), ".syswarden-removal-") {
			t.Fatalf("quarantine remains after exact removal: %s", entry.Name())
		}
	}
}

func TestExactOwnedArtifactRemovalPreservesModifiedBytesWithWarning_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	expected := []byte("managed\n")
	modified := []byte("operator\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", expected, 0600)
	path := filepath.Join(parent, directoryName, expectation.name)
	writeOwnedArtifactFixture(t, path, modified, 0600)

	warnings := []string{}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent,
		directoryName,
		uid,
		gid,
		expectation,
		quietOwnedArtifactRemovalOptions(&warnings),
	)
	if err != nil || removed {
		t.Fatalf("modified removal = %t, %v", removed, err)
	}
	if len(warnings) != 1 || !strings.Contains(warnings[0], "Preserving") {
		t.Fatalf("modified warnings = %v", warnings)
	}
	if got, err := os.ReadFile(path); err != nil || !bytes.Equal(got, modified) { // #nosec G304 -- path is confined to the private modified-artifact fixture root
		t.Fatalf("modified artifact bytes = %q, %v", got, err)
	}
}

func TestExactOwnedArtifactRemovalPreservesUnsafeFileKindsAndLinks_SW2_PKG_001(t *testing.T) {
	content := []byte("managed\n")
	tests := []struct {
		name string
		seed func(*testing.T, string)
	}{
		{
			name: "symlink",
			seed: func(t *testing.T, path string) {
				t.Helper()
				target := filepath.Join(filepath.Dir(path), "operator-target")
				writeOwnedArtifactFixture(t, target, content, 0600)
				if err := os.Symlink(target, path); err != nil {
					t.Fatalf("create symlink fixture: %v", err)
				}
			},
		},
		{
			name: "fifo",
			seed: func(t *testing.T, path string) {
				t.Helper()
				if err := unix.Mkfifo(path, 0600); err != nil {
					t.Fatalf("create FIFO fixture: %v", err)
				}
			},
		},
		{
			name: "hardlink",
			seed: func(t *testing.T, path string) {
				t.Helper()
				writeOwnedArtifactFixture(t, path, content, 0600)
				if err := os.Link(path, filepath.Join(filepath.Dir(path), "operator-link")); err != nil {
					t.Fatalf("create hardlink fixture: %v", err)
				}
			},
		},
		{
			name: "mode",
			seed: func(t *testing.T, path string) {
				t.Helper()
				writeOwnedArtifactFixture(t, path, content, 0644)
			},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
			expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
			path := filepath.Join(parent, directoryName, expectation.name)
			test.seed(t, path)
			warnings := []string{}
			removed, err := removeExactOwnedArtifactAtUsing(
				parent,
				directoryName,
				uid,
				gid,
				expectation,
				quietOwnedArtifactRemovalOptions(&warnings),
			)
			if err != nil || removed {
				t.Fatalf("unsafe %s removal = %t, %v", test.name, removed, err)
			}
			if len(warnings) != 1 {
				t.Fatalf("unsafe %s warnings = %v", test.name, warnings)
			}
			if _, err := os.Lstat(path); err != nil {
				t.Fatalf("unsafe %s artifact was not preserved: %v", test.name, err)
			}
		})
	}
}

func TestExactOwnedArtifactInspectionRejectsWrongOwner_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	content := []byte("managed\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	writeOwnedArtifactFixture(
		t,
		filepath.Join(parent, directoryName, expectation.name),
		content,
		0600,
	)
	directory, exists, err := openExistingOwnedArtifactDirectoryAt(parent, directoryName, uid, gid)
	if err != nil || !exists {
		t.Fatalf("open owner fixture = %t, %v", exists, err)
	}
	defer directory.Close()
	inspection, err := inspectExactOwnedArtifact(directory, expectation.name, expectation, uid+1, gid)
	if err != nil || inspection.exact || !strings.Contains(inspection.ambiguous, "owner") {
		t.Fatalf("wrong-owner inspection = %#v, %v", inspection, err)
	}
}

func TestExactOwnedArtifactRemovalRefusesSymlinkedDirectory_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	outside := t.TempDir()
	if err := os.Symlink(outside, filepath.Join(parent, "managed.d")); err != nil {
		t.Fatalf("create directory symlink: %v", err)
	}
	info, err := os.Stat(parent)
	if err != nil {
		t.Fatal(err)
	}
	stat := info.Sys().(*syscall.Stat_t)
	_, err = removeExactOwnedArtifactAtUsing(
		parent,
		"managed.d",
		stat.Uid,
		stat.Gid,
		exactContentExpectation("test generated artifact", "managed.conf", []byte("managed\n"), 0600),
		defaultExactOwnedArtifactRemovalOptions(),
	)
	if err == nil || !strings.Contains(err.Error(), "without following symlinks") {
		t.Fatalf("symlinked directory refusal = %v", err)
	}
}

func TestExactOwnedArtifactRemovalDetectsPreQuarantineSwap_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	content := []byte("managed\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	directory := filepath.Join(parent, directoryName)
	path := filepath.Join(directory, expectation.name)
	backup := filepath.Join(directory, "managed.original")
	writeOwnedArtifactFixture(t, path, content, 0600)

	options := defaultExactOwnedArtifactRemovalOptions()
	options.warn = func(string) {}
	swapped := false
	options.faultPoint = func(point string) {
		if point != "before-rename:"+expectation.name || swapped {
			return
		}
		swapped = true
		if err := os.Rename(path, backup); err != nil {
			t.Fatalf("preserve original during swap: %v", err)
		}
		writeOwnedArtifactFixture(t, path, content, 0600)
	}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent,
		directoryName,
		uid,
		gid,
		expectation,
		options,
	)
	if err == nil || removed || !strings.Contains(err.Error(), "changed before quarantine") {
		t.Fatalf("pre-quarantine swap result = %t, %v", removed, err)
	}
	if !swapped {
		t.Fatal("pre-quarantine swap boundary was not reached")
	}
	for _, preserved := range []string{path, backup} {
		if _, err := os.Lstat(preserved); err != nil {
			t.Fatalf("swapped artifact %s was not preserved: %v", preserved, err)
		}
	}
}

func TestExactOwnedArtifactRemovalRefusesConcurrentOriginalReplacement_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	content := []byte("managed\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	directory := filepath.Join(parent, directoryName)
	path := filepath.Join(directory, expectation.name)
	writeOwnedArtifactFixture(t, path, content, 0600)

	options := defaultExactOwnedArtifactRemovalOptions()
	options.warn = func(string) {}
	originalRename := options.renameat2
	exchangeCalls := 0
	options.renameat2 = func(oldDirectory int, oldName string, newDirectory int, newName string, flags uint) error {
		if flags == unix.RENAME_EXCHANGE {
			exchangeCalls++
		}
		return originalRename(oldDirectory, oldName, newDirectory, newName, flags)
	}
	replaced := false
	options.faultPoint = func(point string) {
		if point == "after-rename:"+expectation.name && !replaced {
			replaced = true
			writeOwnedArtifactFixture(t, path, []byte("operator\n"), 0600)
		}
	}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent,
		directoryName,
		uid,
		gid,
		expectation,
		options,
	)
	if err == nil || removed || !strings.Contains(err.Error(), "appeared concurrently") {
		t.Fatalf("concurrent replacement result = %t, %v", removed, err)
	}
	if got, readErr := os.ReadFile(path); readErr != nil || string(got) != "operator\n" { // #nosec G304 -- path is confined to the private concurrent-replacement fixture root
		t.Fatalf("concurrent replacement = %q, %v", got, readErr)
	}
	if exchangeCalls != 0 {
		t.Fatalf("concurrent replacement was displaced by %d exchange operations", exchangeCalls)
	}
	entries, readErr := os.ReadDir(directory)
	if readErr != nil {
		t.Fatal(readErr)
	}
	quarantines := 0
	preserved := 0
	for _, entry := range entries {
		if strings.Contains(entry.Name(), ".syswarden-removal-") {
			quarantines++
		}
		if strings.Contains(entry.Name(), ".syswarden-preserved-") {
			preserved++
			got, err := os.ReadFile(filepath.Join(directory, entry.Name())) // #nosec G304 -- entry came from ReadDir on the private quarantine fixture
			if err != nil || !bytes.Equal(got, content) {
				t.Fatalf("preserved exact bytes = %q, %v", got, err)
			}
		}
	}
	if quarantines != 1 || preserved != 0 {
		t.Fatalf("recoverable quarantine / extra preservation count = %d/%d, want 1/0", quarantines, preserved)
	}
}

func TestExactOwnedArtifactRemovalRefusesQuarantineSwapBeforeUnlink_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	content := []byte("managed\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	directory := filepath.Join(parent, directoryName)
	path := filepath.Join(directory, expectation.name)
	writeOwnedArtifactFixture(t, path, content, 0600)

	options := defaultExactOwnedArtifactRemovalOptions()
	options.warn = func(string) {}
	swapped := false
	options.faultPoint = func(point string) {
		if point != "before-unlink:"+expectation.name || swapped {
			return
		}
		swapped = true
		entries, err := os.ReadDir(directory)
		if err != nil {
			t.Fatalf("read quarantine directory: %v", err)
		}
		for _, entry := range entries {
			if !strings.Contains(entry.Name(), ".syswarden-removal-") {
				continue
			}
			quarantine := filepath.Join(directory, entry.Name())
			if err := os.Rename(quarantine, filepath.Join(directory, "managed.exact-backup")); err != nil {
				t.Fatalf("preserve exact quarantine: %v", err)
			}
			writeOwnedArtifactFixture(t, quarantine, []byte("operator\n"), 0600)
			return
		}
		t.Fatal("pre-unlink quarantine was not found")
	}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent,
		directoryName,
		uid,
		gid,
		expectation,
		options,
	)
	if err == nil || removed || !strings.Contains(err.Error(), "quarantined test generated artifact changed") {
		t.Fatalf("quarantine swap result = %t, %v", removed, err)
	}
	if !swapped {
		t.Fatal("pre-unlink quarantine swap boundary was not reached")
	}
	if _, err := os.Lstat(filepath.Join(directory, "managed.exact-backup")); err != nil {
		t.Fatalf("exact quarantine backup was not preserved: %v", err)
	}
	if _, err := os.Lstat(path); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("original name unexpectedly exists: %v", err)
	}
}

func TestExactOwnedArtifactRemovalRestoresAfterRenameSyncFailure_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	content := []byte("managed\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	path := filepath.Join(parent, directoryName, expectation.name)
	writeOwnedArtifactFixture(t, path, content, 0600)

	sentinel := errors.New("synthetic quarantine sync failure")
	options := defaultExactOwnedArtifactRemovalOptions()
	originalSync := options.syncDirectory
	syncCalls := 0
	options.syncDirectory = func(directory *os.File) error {
		syncCalls++
		if syncCalls == 1 {
			return sentinel
		}
		return originalSync(directory)
	}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent, directoryName, uid, gid, expectation, options,
	)
	if err == nil || !errors.Is(err, sentinel) || removed {
		t.Fatalf("rename-sync rollback = %t, %v", removed, err)
	}
	if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, content) { // #nosec G304 -- path is confined to the private rename-rollback fixture root
		t.Fatalf("rename-sync restored bytes = %q, %v", got, readErr)
	}
}

func TestExactOwnedArtifactRemovalRunsRecoveryHookWhenRestoreSyncFails_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	content := []byte("managed\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	path := filepath.Join(parent, directoryName, expectation.name)
	writeOwnedArtifactFixture(t, path, content, 0600)

	sentinel := errors.New("synthetic durability failure")
	options := defaultExactOwnedArtifactRemovalOptions()
	options.syncDirectory = func(*os.File) error { return sentinel }
	recoveryCalls := 0
	options.afterRestore = func() error {
		recoveryCalls++
		return nil
	}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent, directoryName, uid, gid, expectation, options,
	)
	if err == nil || !errors.Is(err, sentinel) || removed {
		t.Fatalf("restore durability failure = %t, %v", removed, err)
	}
	if recoveryCalls != 1 {
		t.Fatalf("recovery hook calls = %d", recoveryCalls)
	}
	if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, content) { // #nosec G304 -- path is confined to the private restore-failure fixture root
		t.Fatalf("restored canonical bytes = %q, %v", got, readErr)
	}
}

func TestExactOwnedArtifactRemovalRestoresAfterUnlinkFailure_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	content := []byte("managed\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	path := filepath.Join(parent, directoryName, expectation.name)
	writeOwnedArtifactFixture(t, path, content, 0600)

	sentinel := errors.New("synthetic unlink failure")
	options := defaultExactOwnedArtifactRemovalOptions()
	originalUnlink := options.unlinkat
	injected := false
	options.unlinkat = func(directory int, name string, flags int) error {
		if !injected && strings.Contains(name, ".syswarden-removal-") {
			injected = true
			return sentinel
		}
		return originalUnlink(directory, name, flags)
	}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent, directoryName, uid, gid, expectation, options,
	)
	if err == nil || !errors.Is(err, sentinel) || removed {
		t.Fatalf("unlink rollback = %t, %v", removed, err)
	}
	if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, content) { // #nosec G304 -- path is confined to the private unlink-rollback fixture root
		t.Fatalf("unlink restored bytes = %q, %v", got, readErr)
	}
}

func TestExactOwnedArtifactRemovalRecreatesAfterPostUnlinkSyncFailure_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	content := []byte("managed\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	path := filepath.Join(parent, directoryName, expectation.name)
	writeOwnedArtifactFixture(t, path, content, 0600)

	sentinel := errors.New("synthetic post-unlink sync failure")
	options := defaultExactOwnedArtifactRemovalOptions()
	originalSync := options.syncDirectory
	syncCalls := 0
	options.syncDirectory = func(directory *os.File) error {
		syncCalls++
		if syncCalls == 2 {
			return sentinel
		}
		return originalSync(directory)
	}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent, directoryName, uid, gid, expectation, options,
	)
	if err == nil || !errors.Is(err, sentinel) || removed {
		t.Fatalf("post-unlink sync recovery = %t, %v", removed, err)
	}
	if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, content) { // #nosec G304 -- path is confined to the private post-unlink recovery fixture root
		t.Fatalf("post-unlink recreated bytes = %q, %v", got, readErr)
	}
}

func TestExactOwnedArtifactRecreationStagesEveryFailureBeforePublication_SW2_PKG_001(t *testing.T) {
	steps := []string{"open", "fchmod", "fchown", "write", "fsync", "close", "reattest", "rename", "directory-sync"}
	for _, step := range steps {
		t.Run(step, func(t *testing.T) {
			parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
			directoryPath := filepath.Join(parent, directoryName)
			directory, exists, err := openExistingOwnedArtifactDirectoryAt(parent, directoryName, uid, gid)
			if err != nil || !exists {
				t.Fatalf("open recreation fixture = %t, %v", exists, err)
			}
			defer directory.Close()
			content := []byte("managed recreation bytes\n")
			expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
			sentinel := fmt.Errorf("synthetic %s failure", step)
			options := defaultExactOwnedArtifactRemovalOptions()
			options.recreationStep = func(current string) error {
				if current == step {
					return sentinel
				}
				return nil
			}
			err = recreateExactOwnedArtifact(
				directory,
				expectation,
				content,
				exactOwnedArtifactIdentity{mode: unix.S_IFREG | 0600},
				uid,
				gid,
				options,
			)
			if err == nil || !errors.Is(err, sentinel) {
				t.Fatalf("recreation step %s error = %v", step, err)
			}
			staging := filepath.Join(directoryPath, "."+expectation.name+exactArtifactRecreationSuffix)
			if _, statErr := os.Lstat(staging); !errors.Is(statErr, os.ErrNotExist) {
				t.Fatalf("recreation step %s left staging: %v", step, statErr)
			}
			canonical := filepath.Join(directoryPath, expectation.name)
			if step == "directory-sync" {
				if got, readErr := os.ReadFile(canonical); readErr != nil || !bytes.Equal(got, content) { // #nosec G304 -- canonical is confined to the private recreation fixture root
					t.Fatalf("post-publication sync failure canonical = %q, %v", got, readErr)
				}
				return
			}
			if _, statErr := os.Lstat(canonical); !errors.Is(statErr, os.ErrNotExist) {
				t.Fatalf("recreation step %s exposed canonical: %v", step, statErr)
			}
		})
	}
}

func TestExactOwnedArtifactRecreationNeverOverwritesConcurrentCanonical_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	directoryPath := filepath.Join(parent, directoryName)
	directory, exists, err := openExistingOwnedArtifactDirectoryAt(parent, directoryName, uid, gid)
	if err != nil || !exists {
		t.Fatalf("open recreation fixture = %t, %v", exists, err)
	}
	defer directory.Close()
	content := []byte("managed recreation bytes\n")
	operator := []byte("operator replacement\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	canonical := filepath.Join(directoryPath, expectation.name)
	options := defaultExactOwnedArtifactRemovalOptions()
	options.recreationStep = func(step string) error {
		if step == "rename" {
			writeOwnedArtifactFixture(t, canonical, operator, 0600)
		}
		return nil
	}
	err = recreateExactOwnedArtifact(
		directory,
		expectation,
		content,
		exactOwnedArtifactIdentity{mode: unix.S_IFREG | 0600},
		uid,
		gid,
		options,
	)
	if err == nil || !errors.Is(err, unix.EEXIST) {
		t.Fatalf("concurrent recreation publication error = %v", err)
	}
	if got, readErr := os.ReadFile(canonical); readErr != nil || !bytes.Equal(got, operator) { // #nosec G304 -- canonical is confined to the private concurrent-publication fixture root
		t.Fatalf("concurrent canonical = %q, %v", got, readErr)
	}
	staging := filepath.Join(directoryPath, "."+expectation.name+exactArtifactRecreationSuffix)
	if _, statErr := os.Lstat(staging); !errors.Is(statErr, os.ErrNotExist) {
		t.Fatalf("concurrent recreation left staging: %v", statErr)
	}
}

func TestExactOwnedArtifactRemovalAcceptsGeneratedConfigBeyond64KiB_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	info, err := os.Stat(parent)
	if err != nil {
		t.Fatal(err)
	}
	stat := info.Sys().(*syscall.Stat_t)
	logDirectory := filepath.Join(parent, "tenant-logs")
	if err := os.Mkdir(logDirectory, 0750); err != nil {
		t.Fatal(err)
	}
	const logCount = 800
	for index := range logCount {
		writeOwnedArtifactFixture(
			t,
			filepath.Join(logDirectory, fmt.Sprintf("tenant-%04d.log", index)),
			nil,
			0600,
		)
	}
	rendered, active, err := renderWAFRsyslogConfig(filepath.Join(logDirectory, "*.log"), false)
	if err != nil || active != logCount {
		t.Fatalf("render large WAF glob = %d, %v", active, err)
	}
	content := []byte(rendered)
	if len(content) <= 64*1024 || len(content) >= rsyslogArtifactContentLimit {
		t.Fatalf("large generated fixture size = %d", len(content))
	}
	changed, err := reconcileRsyslogArtifactAtUsing(
		parent,
		wafRsyslogConfigName,
		stat.Uid,
		stat.Gid,
		content,
		nil,
		func(directory *os.File) error { return directory.Sync() },
	)
	if err != nil || !changed {
		t.Fatalf("publish >64KiB generated config = %t, %v", changed, err)
	}
	removed, err := removeExpectedRsyslogArtifactAtUsing(
		parent,
		stat.Uid,
		stat.Gid,
		exactContentExpectation("large WAF bridge", wafRsyslogConfigName, content, 0600),
		defaultExactOwnedArtifactRemovalOptions(),
	)
	if err != nil || !removed {
		t.Fatalf("remove >64KiB generated config = %t, %v", removed, err)
	}
}

func TestExactOwnedArtifactRemovalNeverOverwritesPostUnlinkReplacement_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	content := []byte("managed\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	path := filepath.Join(parent, directoryName, expectation.name)
	writeOwnedArtifactFixture(t, path, content, 0600)

	operatorBytes := []byte("operator\n")
	options := defaultExactOwnedArtifactRemovalOptions()
	options.faultPoint = func(point string) {
		if point == "after-unlink:"+expectation.name {
			writeOwnedArtifactFixture(t, path, operatorBytes, 0600)
		}
	}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent, directoryName, uid, gid, expectation, options,
	)
	if err == nil || removed {
		t.Fatalf("post-unlink replacement result = %t, %v", removed, err)
	}
	if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, operatorBytes) { // #nosec G304 -- path is confined to the private post-unlink adversary fixture root
		t.Fatalf("post-unlink operator replacement = %q, %v", got, readErr)
	}
}

func TestExactOwnedArtifactRemovalRecoversDeterministicQuarantineAfterCrash_SW2_PKG_001(t *testing.T) {
	tests := []struct {
		name              string
		faultPoint        string
		panicBeforeCommit bool
		wantInitialCommit int
	}{
		{name: "after rename", faultPoint: "after-rename:managed.conf"},
		{name: "inside before commit", panicBeforeCommit: true},
		{name: "after successful before commit", faultPoint: "after-before-commit:managed.conf", wantInitialCommit: 1},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
			content := []byte("managed\n")
			expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
			directory := filepath.Join(parent, directoryName)
			canonical := filepath.Join(directory, expectation.name)
			quarantine := filepath.Join(directory, exactArtifactQuarantineName(expectation.name))
			writeOwnedArtifactFixture(t, canonical, content, 0600)

			commitCalls := 0
			options := defaultExactOwnedArtifactRemovalOptions()
			options.beforeCommit = func() error {
				commitCalls++
				if test.panicBeforeCommit {
					panic("synthetic before-commit crash")
				}
				return nil
			}
			options.faultPoint = func(point string) {
				if point == test.faultPoint {
					panic("synthetic removal crash")
				}
			}
			panicked := false
			func() {
				defer func() {
					panicked = recover() != nil
				}()
				_, _ = removeExactOwnedArtifactAtUsing(
					parent, directoryName, uid, gid, expectation, options,
				)
			}()
			if !panicked {
				t.Fatal("synthetic crash boundary was not reached")
			}
			if commitCalls != test.wantInitialCommit && !test.panicBeforeCommit {
				t.Fatalf("initial before-commit calls = %d", commitCalls)
			}
			if _, err := os.Lstat(canonical); !errors.Is(err, os.ErrNotExist) {
				t.Fatalf("canonical path after crash = %v", err)
			}
			if got, err := os.ReadFile(quarantine); err != nil || !bytes.Equal(got, content) { // #nosec G304 -- quarantine is confined to the private crash-recovery fixture root
				t.Fatalf("durable crash quarantine = %q, %v", got, err)
			}

			retryCalls := 0
			retry := defaultExactOwnedArtifactRemovalOptions()
			retry.beforeCommit = func() error {
				retryCalls++
				return nil
			}
			removed, err := removeExactOwnedArtifactAtUsing(
				parent, directoryName, uid, gid, expectation, retry,
			)
			if err != nil || !removed {
				t.Fatalf("crash recovery = %t, %v", removed, err)
			}
			if retryCalls != 1 {
				t.Fatalf("retry before-commit calls = %d", retryCalls)
			}
			for _, path := range []string{canonical, quarantine} {
				if _, err := os.Lstat(path); !errors.Is(err, os.ErrNotExist) {
					t.Fatalf("path remains after crash recovery %s: %v", path, err)
				}
			}
		})
	}
}

func TestExactOwnedArtifactRecoveryPreservesCanonicalReplacementAndQuarantine_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	content := []byte("managed\n")
	operatorBytes := []byte("operator\n")
	expectation := exactContentExpectation("test generated artifact", "managed.conf", content, 0600)
	directory := filepath.Join(parent, directoryName)
	canonical := filepath.Join(directory, expectation.name)
	quarantine := filepath.Join(directory, exactArtifactQuarantineName(expectation.name))
	writeOwnedArtifactFixture(t, canonical, operatorBytes, 0600)
	writeOwnedArtifactFixture(t, quarantine, content, 0600)

	recoveryCalls := 0
	options := defaultExactOwnedArtifactRemovalOptions()
	options.afterRestore = func() error {
		recoveryCalls++
		return nil
	}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent, directoryName, uid, gid, expectation, options,
	)
	if err == nil || removed || !strings.Contains(err.Error(), "both canonical") {
		t.Fatalf("canonical/quarantine conflict = %t, %v", removed, err)
	}
	if recoveryCalls != 1 {
		t.Fatalf("conflict recovery hook calls = %d", recoveryCalls)
	}
	for path, want := range map[string][]byte{canonical: operatorBytes, quarantine: content} {
		if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, want) { // #nosec G304 -- path is selected from two fixed names beneath the private conflict fixture root
			t.Fatalf("preserved conflict path %s = %q, %v", path, got, readErr)
		}
	}
}

func TestExactOwnedArtifactRecoveryBlocksAmbiguousQuarantine_SW2_PKG_001(t *testing.T) {
	parent, directoryName, uid, gid := newOwnedArtifactRemovalFixture(t)
	expectation := exactContentExpectation("test generated artifact", "managed.conf", []byte("managed\n"), 0600)
	quarantine := filepath.Join(parent, directoryName, exactArtifactQuarantineName(expectation.name))
	writeOwnedArtifactFixture(t, quarantine, []byte("operator\n"), 0600)

	recoveryCalls := 0
	options := defaultExactOwnedArtifactRemovalOptions()
	options.afterRestore = func() error {
		recoveryCalls++
		return nil
	}
	removed, err := removeExactOwnedArtifactAtUsing(
		parent, directoryName, uid, gid, expectation, options,
	)
	if err == nil || removed || !strings.Contains(err.Error(), "ambiguous recovery quarantine") {
		t.Fatalf("ambiguous quarantine recovery = %t, %v", removed, err)
	}
	if recoveryCalls != 1 {
		t.Fatalf("ambiguous recovery hook calls = %d", recoveryCalls)
	}
	if got, readErr := os.ReadFile(quarantine); readErr != nil || string(got) != "operator\n" { // #nosec G304 -- quarantine is confined to the private ambiguous-recovery fixture root
		t.Fatalf("ambiguous quarantine = %q, %v", got, readErr)
	}
}

func TestGeneratedRsyslogRemovalReactivatesAndPropagatesServiceFailure_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	parentInfo, err := os.Stat(parent)
	if err != nil {
		t.Fatal(err)
	}
	stat := parentInfo.Sys().(*syscall.Stat_t)
	activeConfig := config.NewFailSafeConfig()
	waf, _, err := renderWAFRsyslogConfig(activeConfig.ModsecLogs, activeConfig.SiemEnabled)
	if err != nil {
		t.Fatal(err)
	}
	writeOwnedArtifactFixture(
		t,
		filepath.Join(directory, wafRsyslogConfigName),
		[]byte(waf),
		0600,
	)

	sentinel := errors.New("synthetic rsyslog activation failure")
	activationCalls := 0
	err = removeOwnedGeneratedArtifactsForPackageRemovalAtUsing(
		activeConfig,
		parent,
		stat.Uid,
		stat.Gid,
		defaultExactOwnedArtifactRemovalOptions(),
		func(changed bool) error {
			activationCalls++
			if !changed {
				t.Fatal("rsyslog removal did not request changed-state activation")
			}
			return sentinel
		},
	)
	if err == nil || !errors.Is(err, sentinel) ||
		!strings.Contains(err.Error(), "validate and reactivate rsyslog") {
		t.Fatalf("rsyslog activation failure = %v", err)
	}
	if activationCalls != 2 {
		t.Fatalf("rsyslog activation calls = %d", activationCalls)
	}
	if got, err := os.ReadFile(filepath.Join(directory, wafRsyslogConfigName)); err != nil || string(got) != waf { // #nosec G304 -- fixed WAF name is beneath the private service-rollback fixture root
		t.Fatalf("WAF configuration rollback = %q, %v", got, err)
	}
}

func TestPackageRemovalRsyslogCleanupForcesRestartWhenFragmentsAreAlreadyAbsent_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	parentInfo, err := os.Stat(parent)
	if err != nil {
		t.Fatal(err)
	}
	stat := parentInfo.Sys().(*syscall.Stat_t)
	restartCalls := 0
	err = removeOwnedRsyslogArtifactsForPackageRemovalAtUsing(
		config.NewFailSafeConfig(),
		parent,
		stat.Uid,
		stat.Gid,
		defaultExactOwnedArtifactRemovalOptions(),
		func(changed bool) error {
			restartCalls++
			if changed {
				t.Fatal("already-absent recovery reported a configuration change")
			}
			return nil
		},
	)
	if err != nil {
		t.Fatalf("already-absent package-removal restart barrier: %v", err)
	}
	if restartCalls != 1 {
		t.Fatalf("already-absent package-removal restart calls = %d, want 1", restartCalls)
	}
}

func TestPackageRemovalRsyslogCleanupRefusesRemainingSocketProducer_SW2_PKG_001(t *testing.T) {
	for _, name := range []string{
		wafRsyslogConfigName,
		exactArtifactQuarantineName(wafRsyslogConfigName),
	} {
		t.Run(name, func(t *testing.T) {
			parent := t.TempDir()
			directory := filepath.Join(parent, wafRsyslogDirectoryName)
			if err := os.Mkdir(directory, 0750); err != nil {
				t.Fatal(err)
			}
			parentInfo, err := os.Stat(parent)
			if err != nil {
				t.Fatal(err)
			}
			stat := parentInfo.Sys().(*syscall.Stat_t)
			path := filepath.Join(directory, name)
			operatorBytes := []byte("operator-owned potential omuxsock producer\n")
			writeOwnedArtifactFixture(t, path, operatorBytes, 0600)
			restartCalls := 0
			err = removeOwnedRsyslogArtifactsForPackageRemovalAtUsing(
				config.NewFailSafeConfig(),
				parent,
				stat.Uid,
				stat.Gid,
				defaultExactOwnedArtifactRemovalOptions(),
				func(bool) error {
					restartCalls++
					return nil
				},
			)
			if err == nil || !strings.Contains(err.Error(), "potential SysWarden rsyslog socket producer") {
				t.Fatalf("remaining producer refusal = %v", err)
			}
			if restartCalls != 0 {
				t.Fatalf("remaining producer triggered %d restart calls", restartCalls)
			}
			if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, operatorBytes) { // #nosec G304 -- path is confined to the private producer fixture root
				t.Fatalf("remaining producer changed: bytes=%q error=%v", got, readErr)
			}
		})
	}
}

func TestOfflinePackageRemovalAcceptsOnlyCompleteAttestedNoopWithoutRestart_SW2_PKG_001(t *testing.T) {
	attestCalls := 0
	restartCalls := 0
	outcome, err := removeOwnedRsyslogArtifactsForPackageRemovalWithRuntimeAtUsing(
		nil,
		"/unused",
		0,
		0,
		defaultExactOwnedArtifactRemovalOptions(),
		func() (string, error) { return "OFFLINE", nil },
		func() error {
			attestCalls++
			return nil
		},
		func(bool) error {
			restartCalls++
			return nil
		},
	)
	if err != nil {
		t.Fatalf("complete offline no-op: %v", err)
	}
	if outcome != RsyslogPackageRemovalOfflineAlreadyComplete {
		t.Fatalf("complete offline no-op outcome = %d", outcome)
	}
	if attestCalls != 1 || restartCalls != 0 {
		t.Fatalf("offline no-op calls = attest %d restart %d", attestCalls, restartCalls)
	}

	sentinel := errors.New("synthetic incomplete offline teardown")
	outcome, err = removeOwnedRsyslogArtifactsForPackageRemovalWithRuntimeAtUsing(
		nil,
		"/unused",
		0,
		0,
		defaultExactOwnedArtifactRemovalOptions(),
		func() (string, error) { return "OFFLINE", nil },
		func() error { return sentinel },
		func(bool) error {
			restartCalls++
			return nil
		},
	)
	if err == nil || !errors.Is(err, sentinel) ||
		!strings.Contains(err.Error(), "completed rsyslog teardown state cannot be attested") {
		t.Fatalf("incomplete offline no-op refusal = %v", err)
	}
	if outcome != RsyslogPackageRemovalOutcomeUnknown {
		t.Fatalf("incomplete offline no-op outcome = %d", outcome)
	}
	if restartCalls != 0 {
		t.Fatalf("incomplete offline no-op executed %d restart calls", restartCalls)
	}
}

func TestOfflinePackageRemovalAttestationRejectsEveryRsyslogTargetWithoutMutation_SW2_PKG_001(t *testing.T) {
	canonicals := []string{
		rsyslogAntiForgingConfigName,
		wafRsyslogConfigName,
		rsyslogSIEMConfigName,
		rsyslogProvenanceName,
		rsyslogSELinuxProvenanceName,
	}
	var targets []string
	for _, canonical := range canonicals {
		targets = append(
			targets,
			canonical,
			exactArtifactQuarantineName(canonical),
			"."+canonical+exactArtifactRecreationSuffix,
			"."+canonical+".syswarden-0123456789abcdef0123456789abcdef.tmp",
		)
	}
	for _, target := range targets {
		t.Run(target, func(t *testing.T) {
			parent := t.TempDir()
			directory := filepath.Join(parent, wafRsyslogDirectoryName)
			if err := os.Mkdir(directory, 0750); err != nil {
				t.Fatal(err)
			}
			parentInfo, err := os.Stat(parent)
			if err != nil {
				t.Fatal(err)
			}
			stat := parentInfo.Sys().(*syscall.Stat_t)
			path := filepath.Join(directory, target)
			content := []byte("preserve offline target exactly\n")
			writeOwnedArtifactFixture(t, path, content, 0600)
			socketCalls := 0
			moduleCalls := 0
			err = attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
				parent,
				stat.Uid,
				stat.Gid,
				func() error {
					socketCalls++
					return nil
				},
				func() (bool, error) { return true, nil },
				func() ([]selinuxModuleIdentity, error) {
					moduleCalls++
					return nil, nil
				},
			)
			if err == nil || !strings.Contains(err.Error(), "rsyslog teardown target") {
				t.Fatalf("offline target %s attestation = %v", target, err)
			}
			if socketCalls != 0 || moduleCalls != 0 {
				t.Fatalf("offline target %s reached later inspectors: socket=%d module=%d", target, socketCalls, moduleCalls)
			}
			if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, content) { // #nosec G304 -- path is confined to the private offline-target fixture root
				t.Fatalf("offline target %s mutated: bytes=%q error=%v", target, got, readErr)
			}
		})
	}
}

func TestOfflinePackageRemovalAttestationRejectsLegacyCompletionTargetsWithoutMutation_SW2_PKG_001(t *testing.T) {
	for _, target := range []string{
		legacyCompletionName,
		exactArtifactQuarantineName(legacyCompletionName),
		"." + legacyCompletionName + exactArtifactRecreationSuffix,
		"." + legacyCompletionName + ".syswarden-0123456789abcdef0123456789abcdef.tmp",
	} {
		t.Run(target, func(t *testing.T) {
			parent := t.TempDir()
			directory := filepath.Join(parent, legacyCompletionDirectoryName)
			if err := os.Mkdir(directory, 0750); err != nil {
				t.Fatal(err)
			}
			parentInfo, err := os.Stat(parent)
			if err != nil {
				t.Fatal(err)
			}
			stat := parentInfo.Sys().(*syscall.Stat_t)
			path := filepath.Join(directory, target)
			content := []byte("preserve legacy completion target exactly\n")
			writeOwnedArtifactFixture(t, path, content, 0600)
			socketCalls := 0
			moduleCalls := 0
			err = attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
				parent,
				stat.Uid,
				stat.Gid,
				func() error {
					socketCalls++
					return nil
				},
				func() (bool, error) { return true, nil },
				func() ([]selinuxModuleIdentity, error) {
					moduleCalls++
					return nil, nil
				},
			)
			if err == nil || !strings.Contains(err.Error(), "legacy completion teardown target") {
				t.Fatalf("offline legacy target %s attestation = %v", target, err)
			}
			if socketCalls != 0 || moduleCalls != 0 {
				t.Fatalf("offline legacy target %s reached later inspectors: socket=%d module=%d", target, socketCalls, moduleCalls)
			}
			if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, content) { // #nosec G304 -- path is confined to the private legacy-target fixture root
				t.Fatalf("offline legacy target %s mutated: bytes=%q error=%v", target, got, readErr)
			}
		})
	}

	t.Run("canonical symlink lookalike", func(t *testing.T) {
		parent := t.TempDir()
		directory := filepath.Join(parent, legacyCompletionDirectoryName)
		if err := os.Mkdir(directory, 0750); err != nil {
			t.Fatal(err)
		}
		parentInfo, err := os.Stat(parent)
		if err != nil {
			t.Fatal(err)
		}
		stat := parentInfo.Sys().(*syscall.Stat_t)
		operator := filepath.Join(t.TempDir(), "operator-completion")
		if err := os.WriteFile(operator, []byte("operator"), 0600); err != nil {
			t.Fatal(err)
		}
		path := filepath.Join(directory, legacyCompletionName)
		if err := os.Symlink(operator, path); err != nil {
			t.Fatal(err)
		}
		err = attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			stat.Uid,
			stat.Gid,
			func() error { return nil },
			func() (bool, error) { return true, nil },
			func() ([]selinuxModuleIdentity, error) { return nil, nil },
		)
		if err == nil || !strings.Contains(err.Error(), "legacy completion teardown target") {
			t.Fatalf("offline legacy symlink refusal = %v", err)
		}
		if target, readErr := os.Readlink(path); readErr != nil || target != operator {
			t.Fatalf("offline legacy symlink mutated: target=%q error=%v", target, readErr)
		}
		if got, readErr := os.ReadFile(operator); readErr != nil || string(got) != "operator" { // #nosec G304 -- operator is confined to the private legacy-symlink fixture root
			t.Fatalf("offline legacy symlink target mutated: bytes=%q error=%v", got, readErr)
		}
	})

	t.Run("ambiguous legacy parent", func(t *testing.T) {
		parent := t.TempDir()
		parentInfo, err := os.Stat(parent)
		if err != nil {
			t.Fatal(err)
		}
		stat := parentInfo.Sys().(*syscall.Stat_t)
		operator := t.TempDir()
		marker := filepath.Join(operator, "keep")
		if err := os.WriteFile(marker, []byte("operator"), 0600); err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(operator, filepath.Join(parent, legacyCompletionDirectoryName)); err != nil {
			t.Fatal(err)
		}
		err = attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			stat.Uid,
			stat.Gid,
			func() error { return nil },
			func() (bool, error) { return true, nil },
			func() ([]selinuxModuleIdentity, error) { return nil, nil },
		)
		if err == nil || !strings.Contains(err.Error(), "legacy completion directory") ||
			!strings.Contains(err.Error(), "without following symlinks") {
			t.Fatalf("ambiguous offline legacy directory refusal = %v", err)
		}
		if got, readErr := os.ReadFile(marker); readErr != nil || string(got) != "operator" { // #nosec G304 -- marker is confined to the private legacy-directory fixture root
			t.Fatalf("ambiguous offline legacy directory mutated operator target: bytes=%q error=%v", got, readErr)
		}
	})
}

func TestOfflinePackageRemovalAttestationRejectsSocketModuleAndInspectionErrors_SW2_PKG_001(t *testing.T) {
	newFixture := func(t *testing.T) (string, uint32, uint32) {
		t.Helper()
		parent := t.TempDir()
		if err := os.Mkdir(filepath.Join(parent, wafRsyslogDirectoryName), 0750); err != nil {
			t.Fatal(err)
		}
		parentInfo, err := os.Stat(parent)
		if err != nil {
			t.Fatal(err)
		}
		stat := parentInfo.Sys().(*syscall.Stat_t)
		return parent, stat.Uid, stat.Gid
	}
	newSemoduleInspectors := func(
		entries map[string]trustedPathMetadata,
		links map[string]string,
	) (trustedPathLstat, trustedPathReadlink) {
		return func(path string) (trustedPathMetadata, error) {
				entry, ok := entries[path]
				if !ok {
					return trustedPathMetadata{}, &os.PathError{Op: "lstat", Path: path, Err: unix.ENOENT}
				}
				return entry, nil
			}, func(path string) (string, error) {
				target, ok := links[path]
				if !ok {
					return "", &os.PathError{Op: "readlink", Path: path, Err: unix.EINVAL}
				}
				return target, nil
			}
	}
	directSemoduleEntries := func() map[string]trustedPathMetadata {
		return map[string]trustedPathMetadata{
			"/":                 {uid: 0, mode: os.ModeDir | 0755},
			"/usr":              {uid: 0, mode: os.ModeDir | 0755},
			"/usr/sbin":         {uid: 0, mode: os.ModeDir | 0755},
			trustedSemodulePath: {uid: 0, mode: 0755},
		}
	}

	t.Run("complete absence", func(t *testing.T) {
		parent, uid, gid := newFixture(t)
		if err := attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			uid,
			gid,
			func() error { return nil },
			func() (bool, error) { return true, nil },
			func() ([]selinuxModuleIdentity, error) { return nil, nil },
		); err != nil {
			t.Fatalf("complete offline absence: %v", err)
		}
	})

	t.Run("semodule strict ENOENT permits a read-only no-op", func(t *testing.T) {
		parent, uid, gid := newFixture(t)
		marker := filepath.Join(parent, "operator-marker")
		if err := os.WriteFile(marker, []byte("preserve"), 0600); err != nil {
			t.Fatal(err)
		}
		moduleCalls := 0
		entries := map[string]trustedPathMetadata{
			"/":         {uid: 0, mode: os.ModeDir | 0755},
			"/usr":      {uid: 0, mode: os.ModeDir | 0755},
			"/usr/sbin": {uid: 0, mode: os.ModeSymlink | 0777},
			"/usr/bin":  {uid: 0, mode: os.ModeDir | 0755},
		}
		lstat, readlink := newSemoduleInspectors(entries, map[string]string{"/usr/sbin": "bin"})
		err := attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			uid,
			gid,
			func() error { return nil },
			func() (bool, error) {
				return inspectTrustedSemoduleForOfflinePackageRemovalUsing(lstat, readlink)
			},
			func() ([]selinuxModuleIdentity, error) {
				moduleCalls++
				return nil, nil
			},
		)
		if err != nil {
			t.Fatalf("semodule ENOENT offline no-op: %v", err)
		}
		if moduleCalls != 0 {
			t.Fatalf("semodule ENOENT reached listing %d times", moduleCalls)
		}
		if got, readErr := os.ReadFile(marker); readErr != nil || string(got) != "preserve" { // #nosec G304 -- marker is confined to the private fixture root
			t.Fatalf("semodule ENOENT no-op mutated marker: bytes=%q error=%v", got, readErr)
		}
	})

	for _, test := range []struct {
		name     string
		lstatErr error
	}{
		{name: "semodule EACCES refuses", lstatErr: unix.EACCES},
		{name: "semodule non-directory path refuses", lstatErr: unix.ENOTDIR},
	} {
		t.Run(test.name, func(t *testing.T) {
			parent, uid, gid := newFixture(t)
			moduleCalls := 0
			entries := directSemoduleEntries()
			lstat, readlink := newSemoduleInspectors(entries, nil)
			err := attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
				parent,
				uid,
				gid,
				func() error { return nil },
				func() (bool, error) {
					return inspectTrustedSemoduleForOfflinePackageRemovalUsing(
						func(path string) (trustedPathMetadata, error) {
							if path == trustedSemodulePath {
								return trustedPathMetadata{}, &os.PathError{Op: "lstat", Path: path, Err: test.lstatErr}
							}
							return lstat(path)
						},
						readlink,
					)
				},
				func() ([]selinuxModuleIdentity, error) {
					moduleCalls++
					return nil, nil
				},
			)
			if err == nil || !errors.Is(err, test.lstatErr) ||
				!strings.Contains(err.Error(), "trusted offline SELinux module tool") {
				t.Fatalf("%s = %v", test.name, err)
			}
			if moduleCalls != 0 {
				t.Fatalf("%s reached module listing %d times", test.name, moduleCalls)
			}
		})
	}

	t.Run("untrusted semodule executable refuses", func(t *testing.T) {
		parent, uid, gid := newFixture(t)
		moduleCalls := 0
		entries := directSemoduleEntries()
		entry := entries[trustedSemodulePath]
		entry.mode = 0644
		entries[trustedSemodulePath] = entry
		lstat, readlink := newSemoduleInspectors(entries, nil)
		err := attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			uid,
			gid,
			func() error { return nil },
			func() (bool, error) {
				return inspectTrustedSemoduleForOfflinePackageRemovalUsing(lstat, readlink)
			},
			func() ([]selinuxModuleIdentity, error) {
				moduleCalls++
				return nil, nil
			},
		)
		if err == nil || !strings.Contains(err.Error(), "not executable") {
			t.Fatalf("untrusted semodule refusal = %v", err)
		}
		if moduleCalls != 0 {
			t.Fatalf("untrusted semodule reached module listing %d times", moduleCalls)
		}
	})

	t.Run("broken final semodule symlink is ambiguous", func(t *testing.T) {
		parent, uid, gid := newFixture(t)
		entries := directSemoduleEntries()
		entries[trustedSemodulePath] = trustedPathMetadata{uid: 0, mode: os.ModeSymlink | 0777}
		entries["/missing"] = trustedPathMetadata{uid: 0, mode: os.ModeDir | 0755}
		lstat, readlink := newSemoduleInspectors(
			entries,
			map[string]string{trustedSemodulePath: "/missing/semodule"},
		)
		moduleCalls := 0
		err := attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			uid,
			gid,
			func() error { return nil },
			func() (bool, error) {
				return inspectTrustedSemoduleForOfflinePackageRemovalUsing(lstat, readlink)
			},
			func() ([]selinuxModuleIdentity, error) {
				moduleCalls++
				return nil, nil
			},
		)
		if err == nil || !strings.Contains(err.Error(), "lstat trusted path component /missing/semodule") {
			t.Fatalf("broken final semodule symlink refusal = %v", err)
		}
		if moduleCalls != 0 {
			t.Fatalf("broken semodule symlink reached module listing %d times", moduleCalls)
		}
	})

	t.Run("trusted semodule requires a complete empty listing", func(t *testing.T) {
		parent, uid, gid := newFixture(t)
		moduleCalls := 0
		lstat, readlink := newSemoduleInspectors(directSemoduleEntries(), nil)
		err := attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			uid,
			gid,
			func() error { return nil },
			func() (bool, error) {
				return inspectTrustedSemoduleForOfflinePackageRemovalUsing(lstat, readlink)
			},
			func() ([]selinuxModuleIdentity, error) {
				moduleCalls++
				return nil, nil
			},
		)
		if err != nil {
			t.Fatalf("trusted semodule with empty listing: %v", err)
		}
		if moduleCalls != 1 {
			t.Fatalf("trusted semodule listing calls = %d", moduleCalls)
		}
	})

	t.Run("socket remains", func(t *testing.T) {
		parent, uid, gid := newFixture(t)
		sentinel := errors.New("synthetic socket target remains")
		moduleCalls := 0
		err := attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			uid,
			gid,
			func() error { return sentinel },
			func() (bool, error) { return true, nil },
			func() ([]selinuxModuleIdentity, error) {
				moduleCalls++
				return nil, nil
			},
		)
		if err == nil || !errors.Is(err, sentinel) || !strings.Contains(err.Error(), "runtime socket absence") {
			t.Fatalf("offline socket refusal = %v", err)
		}
		if moduleCalls != 0 {
			t.Fatalf("offline socket refusal reached module inspection %d times", moduleCalls)
		}
	})

	t.Run("SELinux module remains", func(t *testing.T) {
		parent, uid, gid := newFixture(t)
		err := attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			uid,
			gid,
			func() error { return nil },
			func() (bool, error) { return true, nil },
			func() ([]selinuxModuleIdentity, error) {
				return []selinuxModuleIdentity{{
					priority: rsyslogSELinuxModulePriority,
					name:     rsyslogSELinuxModuleName,
				}}, nil
			},
		)
		if err == nil || !strings.Contains(err.Error(), "SELinux module syswarden_rsyslog remains") {
			t.Fatalf("offline SELinux module refusal = %v", err)
		}
	})

	t.Run("SELinux module exists at another priority", func(t *testing.T) {
		parent, uid, gid := newFixture(t)
		err := attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			uid,
			gid,
			func() error { return nil },
			func() (bool, error) { return true, nil },
			func() ([]selinuxModuleIdentity, error) {
				return []selinuxModuleIdentity{{
					priority: 300,
					name:     rsyslogSELinuxModuleName,
					language: rsyslogSELinuxModuleLanguage,
					enabled:  true,
				}}, nil
			},
		)
		if err == nil || !strings.Contains(err.Error(), "operator instance exists at priority 300") {
			t.Fatalf("offline alternate-priority module refusal = %v", err)
		}
	})

	t.Run("module inspection error", func(t *testing.T) {
		parent, uid, gid := newFixture(t)
		sentinel := errors.New("synthetic semodule listing failure")
		err := attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			uid,
			gid,
			func() error { return nil },
			func() (bool, error) { return true, nil },
			func() ([]selinuxModuleIdentity, error) { return nil, sentinel },
		)
		if err == nil || !errors.Is(err, sentinel) || !strings.Contains(err.Error(), "SELinux module absence") {
			t.Fatalf("offline module inspection refusal = %v", err)
		}
	})

	t.Run("ambiguous SELinux module identity", func(t *testing.T) {
		parent, uid, gid := newFixture(t)
		identity := selinuxModuleIdentity{
			priority: rsyslogSELinuxModulePriority,
			name:     rsyslogSELinuxModuleName,
		}
		err := attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			uid,
			gid,
			func() error { return nil },
			func() (bool, error) { return true, nil },
			func() ([]selinuxModuleIdentity, error) {
				return []selinuxModuleIdentity{identity, identity}, nil
			},
		)
		if err == nil || !strings.Contains(err.Error(), "duplicate priority 400 SELinux module identity") {
			t.Fatalf("ambiguous offline module refusal = %v", err)
		}
	})

	t.Run("ambiguous rsyslog directory", func(t *testing.T) {
		parent := t.TempDir()
		parentInfo, err := os.Stat(parent)
		if err != nil {
			t.Fatal(err)
		}
		stat := parentInfo.Sys().(*syscall.Stat_t)
		operator := t.TempDir()
		marker := filepath.Join(operator, "keep")
		if err := os.WriteFile(marker, []byte("operator"), 0600); err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(operator, filepath.Join(parent, wafRsyslogDirectoryName)); err != nil {
			t.Fatal(err)
		}
		socketCalls := 0
		err = attestCompletedRsyslogTeardownForOfflinePackageRemovalAtUsing(
			parent,
			stat.Uid,
			stat.Gid,
			func() error {
				socketCalls++
				return nil
			},
			func() (bool, error) { return true, nil },
			func() ([]selinuxModuleIdentity, error) { return nil, nil },
		)
		if err == nil || !strings.Contains(err.Error(), "without following symlinks") {
			t.Fatalf("ambiguous offline directory refusal = %v", err)
		}
		if socketCalls != 0 {
			t.Fatalf("ambiguous offline directory reached socket inspection %d times", socketCalls)
		}
		if got, readErr := os.ReadFile(marker); readErr != nil || string(got) != "operator" { // #nosec G304 -- marker is confined to the private ambiguity fixture root
			t.Fatalf("ambiguous offline directory mutated operator target: bytes=%q error=%v", got, readErr)
		}
	})
}

func TestGeneratedRsyslogRemovalSkipsDisabledSIEMArtifact_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	parentInfo, err := os.Stat(parent)
	if err != nil {
		t.Fatal(err)
	}
	stat := parentInfo.Sys().(*syscall.Stat_t)
	operatorSIEM := []byte("operator-owned SIEM state\n")
	siemPath := filepath.Join(directory, rsyslogSIEMConfigName)
	writeOwnedArtifactFixture(t, siemPath, operatorSIEM, 0600)

	activationCalls := 0
	err = removeOwnedGeneratedArtifactsForPackageRemovalAtUsing(
		config.NewFailSafeConfig(),
		parent,
		stat.Uid,
		stat.Gid,
		defaultExactOwnedArtifactRemovalOptions(),
		func(bool) error {
			activationCalls++
			return nil
		},
	)
	if err != nil {
		t.Fatalf("disabled SIEM cleanup: %v", err)
	}
	if activationCalls != 0 {
		t.Fatalf("disabled SIEM triggered %d rsyslog activations", activationCalls)
	}
	if got, err := os.ReadFile(siemPath); err != nil || !bytes.Equal(got, operatorSIEM) { // #nosec G304 -- siemPath is confined to the private disabled-SIEM fixture root
		t.Fatalf("disabled SIEM artifact = %q, %v", got, err)
	}
}

func TestGeneratedRsyslogRemovalAcceptsCurrentAndV4032WAFWithoutProvenanceWhenSIEMEnabled_SW2_PKG_001(t *testing.T) {
	activeConfig := config.NewFailSafeConfig()
	activeConfig.SiemEnabled = true
	activeConfig.SiemIP = "192.0.2.40"
	activeConfig.SiemPort = "514"
	activeConfig.SiemProto = "udp"
	current, _, err := renderWAFRsyslogConfig(activeConfig.ModsecLogs, true)
	if err != nil {
		t.Fatal(err)
	}
	legacy, _, err := renderLegacyV4032WAFRsyslogConfig(activeConfig.ModsecLogs)
	if err != nil {
		t.Fatal(err)
	}
	if current == legacy {
		t.Fatal("current SIEM-enabled and legacy WAF fixtures are identical")
	}
	for name, rendered := range map[string]string{
		"current":        current,
		"legacy v4.03.2": legacy,
	} {
		t.Run(name, func(t *testing.T) {
			parent := t.TempDir()
			directory := filepath.Join(parent, wafRsyslogDirectoryName)
			if err := os.Mkdir(directory, 0750); err != nil {
				t.Fatal(err)
			}
			parentInfo, err := os.Stat(parent)
			if err != nil {
				t.Fatal(err)
			}
			stat := parentInfo.Sys().(*syscall.Stat_t)
			path := filepath.Join(directory, wafRsyslogConfigName)
			writeOwnedArtifactFixture(t, path, []byte(rendered), 0600)
			activationCalls := 0
			removeErr := removeOwnedGeneratedArtifactsForPackageRemovalAtUsing(
				activeConfig,
				parent,
				stat.Uid,
				stat.Gid,
				defaultExactOwnedArtifactRemovalOptions(),
				func(changed bool) error {
					if !changed {
						t.Fatal("WAF removal did not request changed-state activation")
					}
					activationCalls++
					return nil
				},
			)
			if removeErr != nil || activationCalls != 1 {
				t.Fatalf("remove unprovenanced WAF variant = calls %d, %v", activationCalls, removeErr)
			}
			if _, statErr := os.Lstat(path); !errors.Is(statErr, os.ErrNotExist) {
				t.Fatalf("unprovenanced WAF variant remains: %v", statErr)
			}
		})
	}
}

func TestGeneratedRsyslogRemovalDeletesExactAntiForgingPolicy_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	parentInfo, err := os.Stat(parent)
	if err != nil {
		t.Fatal(err)
	}
	stat := parentInfo.Sys().(*syscall.Stat_t)
	path := filepath.Join(directory, rsyslogAntiForgingConfigName)
	writeOwnedArtifactFixture(t, path, []byte(security.RsyslogAntiForgingPolicy), 0600)

	activationCalls := 0
	err = removeOwnedGeneratedArtifactsForPackageRemovalAtUsing(
		config.NewFailSafeConfig(),
		parent,
		stat.Uid,
		stat.Gid,
		defaultExactOwnedArtifactRemovalOptions(),
		func(changed bool) error {
			activationCalls++
			if !changed {
				t.Fatal("anti-forging removal did not request changed-state activation")
			}
			return nil
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if activationCalls != 1 {
		t.Fatalf("rsyslog activation calls = %d, want 1", activationCalls)
	}
	if _, err := os.Lstat(path); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("anti-forging policy remains after exact removal: %v", err)
	}
}

func TestLegacyCompletionAttestationConstantsMatchApprovedOutput_SW2_PKG_001(t *testing.T) {
	expectation := legacyCompletionExpectation()
	if expectation.size != 16339 || fmt.Sprintf("%x", expectation.digest) != legacyCompletionSHA256 {
		t.Fatalf("legacy completion identity = size %d digest %x", expectation.size, expectation.digest)
	}
	if _, allowed := expectation.permittedModes[0644]; !allowed || len(expectation.permittedModes) != 1 {
		t.Fatalf("legacy completion modes = %v", expectation.permittedModes)
	}
	if expectation.digest == sha256.Sum256(nil) {
		t.Fatal("legacy completion digest unexpectedly matches empty content")
	}
}

func TestLegacyCompletionPreservesAmbiguousDirectoryWithWarning_SW2_PKG_001(t *testing.T) {
	tests := []struct {
		name string
		seed func(*testing.T, string) string
	}{
		{
			name: "symlink",
			seed: func(t *testing.T, parent string) string {
				t.Helper()
				target := filepath.Join(t.TempDir(), legacyCompletionDirectoryName)
				if err := os.Mkdir(target, 0750); err != nil {
					t.Fatal(err)
				}
				operator := filepath.Join(target, legacyCompletionName)
				writeOwnedArtifactFixture(t, operator, []byte("operator completion\n"), 0644)
				if err := os.Symlink(target, filepath.Join(parent, legacyCompletionDirectoryName)); err != nil {
					t.Fatal(err)
				}
				return operator
			},
		},
		{
			name: "group-writable",
			seed: func(t *testing.T, parent string) string {
				t.Helper()
				directory := filepath.Join(parent, legacyCompletionDirectoryName)
				if err := os.Mkdir(directory, 0770); err != nil { // #nosec G301 -- group-writable adversary is confined to a private t.TempDir fixture
					t.Fatal(err)
				}
				if err := os.Chmod(directory, 0770); err != nil { // #nosec G302 -- group-writable adversary is confined to a private t.TempDir fixture
					t.Fatal(err)
				}
				operator := filepath.Join(directory, legacyCompletionName)
				writeOwnedArtifactFixture(t, operator, []byte("operator completion\n"), 0644)
				return operator
			},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			parent := t.TempDir()
			uid, gid := testOwnedParentIdentity(t, parent)
			operator := test.seed(t, parent)
			warnings := []string{}
			removed, err := removeExactLegacyBashCompletionAtUsing(
				parent, uid, gid, quietOwnedArtifactRemovalOptions(&warnings),
			)
			if err != nil || removed {
				t.Fatalf("ambiguous completion directory removal = %t, %v", removed, err)
			}
			if len(warnings) != 1 || !strings.Contains(warnings[0], "Preserving") {
				t.Fatalf("ambiguous completion directory warnings = %v", warnings)
			}
			if got, readErr := os.ReadFile(operator); readErr != nil || string(got) != "operator completion\n" { // #nosec G304 -- operator is confined to the private ambiguous-completion fixture root
				t.Fatalf("ambiguous completion target = %q, %v", got, readErr)
			}
		})
	}
}
