//go:build linux

package integration

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"syswarden-cli/config"
	"testing"
	"time"

	"golang.org/x/sys/unix"
)

func testOwnedParentIdentity(t *testing.T, parent string) (uint32, uint32) {
	t.Helper()
	info, err := os.Stat(parent)
	if err != nil {
		t.Fatal(err)
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		t.Fatal("test parent has no Linux stat metadata")
	}
	return stat.Uid, stat.Gid
}

func allowTestRsyslogMutation() error { return nil }

func TestRsyslogProvenanceRegistryIsAtomicPrivateAndCanonical_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	waf := []byte("historical WAF bytes\n")
	siem := []byte("historical SIEM bytes\n")
	writeOwnedArtifactFixture(t, filepath.Join(directory, wafRsyslogConfigName), waf, 0600)
	if err := recordRsyslogArtifactProvenanceAtUsing(
		parent, uid, gid, wafRsyslogConfigName, waf,
		func(directory *os.File) error { return directory.Sync() },
	); err != nil {
		t.Fatalf("record WAF provenance: %v", err)
	}
	writeOwnedArtifactFixture(t, filepath.Join(directory, rsyslogSIEMConfigName), siem, 0600)
	if err := recordRsyslogArtifactProvenanceAtUsing(
		parent, uid, gid, rsyslogSIEMConfigName, siem,
		func(directory *os.File) error { return directory.Sync() },
	); err != nil {
		t.Fatalf("record SIEM provenance: %v", err)
	}

	registry, err := readRsyslogProvenanceRegistryAtUsing(parent, uid, gid)
	if err != nil || !registry.exists || len(registry.records) != 2 {
		t.Fatalf("read provenance registry = %#v, %v", registry, err)
	}
	for name, want := range map[string][]byte{
		wafRsyslogConfigName:  waf,
		rsyslogSIEMConfigName: siem,
	} {
		record, exists := registry.records[name]
		if !exists || record.size != int64(len(want)) || record.digest != sha256.Sum256(want) {
			t.Fatalf("provenance record %s = %#v", name, record)
		}
	}
	registryPath := filepath.Join(directory, rsyslogProvenanceName)
	info, err := os.Lstat(registryPath)
	if err != nil {
		t.Fatal(err)
	}
	stat := info.Sys().(*syscall.Stat_t)
	if !info.Mode().IsRegular() || info.Mode().Perm() != 0600 || stat.Uid != uid || stat.Gid != gid || stat.Nlink != 1 {
		t.Fatalf("registry metadata = mode %v uid:gid %d:%d nlink %d", info.Mode(), stat.Uid, stat.Gid, stat.Nlink)
	}
	canonical, err := renderRsyslogProvenanceRegistry(registry.records)
	if err != nil || !bytes.Equal(canonical, registry.content) {
		t.Fatalf("registry canonical bytes = %q, %v", registry.content, err)
	}
	entries, err := os.ReadDir(directory)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if strings.HasSuffix(entry.Name(), ".tmp") {
			t.Fatalf("registry publication left staging file %s", entry.Name())
		}
	}
}

func TestRsyslogProvenanceRefusesSymlinkWithoutTouchingTarget_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	waf := []byte("managed WAF bytes\n")
	writeOwnedArtifactFixture(t, filepath.Join(directory, wafRsyslogConfigName), waf, 0600)
	operator := []byte("operator registry target\n")
	target := filepath.Join(parent, "operator-target")
	writeOwnedArtifactFixture(t, target, operator, 0600)
	if err := os.Symlink(target, filepath.Join(directory, rsyslogProvenanceName)); err != nil {
		t.Fatal(err)
	}
	err := recordRsyslogArtifactProvenanceAtUsing(
		parent, uid, gid, wafRsyslogConfigName, waf,
		func(directory *os.File) error { return directory.Sync() },
	)
	if err == nil {
		t.Fatal("symlinked provenance registry was accepted")
	}
	if got, readErr := os.ReadFile(target); readErr != nil || !bytes.Equal(got, operator) { // #nosec G304 -- target is confined to the private symlink-adversary fixture root
		t.Fatalf("operator target = %q, %v", got, readErr)
	}
}

func TestGeneratedRsyslogRemovalUsesHistoricalProvenanceWhenConfigChangedAndSIEMDisabled_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	historicalWAF := []byte("historical WAF generated bytes\n")
	historicalSIEM := []byte("historical SIEM generated bytes\n")
	for name, content := range map[string][]byte{
		wafRsyslogConfigName:  historicalWAF,
		rsyslogSIEMConfigName: historicalSIEM,
	} {
		writeOwnedArtifactFixture(t, filepath.Join(directory, name), content, 0600)
		if err := recordRsyslogArtifactProvenanceAtUsing(
			parent, uid, gid, name, content,
			func(directory *os.File) error { return directory.Sync() },
		); err != nil {
			t.Fatalf("record provenance for %s: %v", name, err)
		}
	}
	activeConfig := config.NewFailSafeConfig()
	activeConfig.ModsecLogs = "/a/different/current/value/*.log"
	activeConfig.SiemEnabled = false
	activationCalls := 0
	err := removeOwnedGeneratedArtifactsForPackageRemovalAtUsing(
		activeConfig,
		parent,
		uid,
		gid,
		defaultExactOwnedArtifactRemovalOptions(),
		func(changed bool) error {
			if !changed {
				t.Fatal("historical cleanup did not request changed-state activation")
			}
			activationCalls++
			return nil
		},
	)
	if err != nil {
		t.Fatalf("historical provenance cleanup: %v", err)
	}
	if activationCalls != 2 {
		t.Fatalf("historical provenance activation calls = %d, want 2", activationCalls)
	}
	for _, name := range []string{wafRsyslogConfigName, rsyslogSIEMConfigName, rsyslogProvenanceName} {
		if _, statErr := os.Lstat(filepath.Join(directory, name)); !errors.Is(statErr, os.ErrNotExist) {
			t.Fatalf("historical artifact %s remains: %v", name, statErr)
		}
	}
}

func TestGeneratedRsyslogRemovalPreservesRegistryForTrackedModifiedArtifact_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	original := []byte("managed historical WAF bytes\n")
	path := filepath.Join(directory, wafRsyslogConfigName)
	writeOwnedArtifactFixture(t, path, original, 0600)
	if err := recordRsyslogArtifactProvenanceAtUsing(
		parent, uid, gid, wafRsyslogConfigName, original,
		func(directory *os.File) error { return directory.Sync() },
	); err != nil {
		t.Fatal(err)
	}
	modified := []byte("operator modified WAF bytes!\n")
	if len(modified) != len(original) {
		t.Fatalf("test fixture lengths differ: %d != %d", len(modified), len(original))
	}
	writeOwnedArtifactFixture(t, path, modified, 0600)
	warnings := []string{}
	options := defaultExactOwnedArtifactRemovalOptions()
	options.warn = func(message string) { warnings = append(warnings, message) }
	activationCalls := 0
	err := removeOwnedGeneratedArtifactsForPackageRemovalAtUsing(
		config.NewFailSafeConfig(),
		parent,
		uid,
		gid,
		options,
		func(bool) error { activationCalls++; return nil },
	)
	if err != nil {
		t.Fatalf("preserve tracked modified artifact: %v", err)
	}
	if activationCalls != 0 {
		t.Fatalf("tracked modified artifact triggered %d rsyslog activations", activationCalls)
	}
	if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, modified) { // #nosec G304 -- path is confined to the private tracked-artifact fixture root
		t.Fatalf("tracked modified artifact changed = %q, %v", got, readErr)
	}
	registry, readErr := readRsyslogProvenanceRegistryAtUsing(parent, uid, gid)
	if readErr != nil || !registry.exists || registry.records[wafRsyslogConfigName].digest != sha256.Sum256(original) {
		t.Fatalf("tracked modified artifact lost provenance = %#v, %v", registry, readErr)
	}
	if len(warnings) < 2 {
		t.Fatalf("tracked modified artifact warnings = %v", warnings)
	}
}

func TestSIEMDisableRemovesExactForwarderReloadsAndRetiresOnlyItsProvenance_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	waf := []byte("managed WAF bytes\n")
	siem := []byte("managed SIEM bytes\n")
	for name, content := range map[string][]byte{
		wafRsyslogConfigName:  waf,
		rsyslogSIEMConfigName: siem,
	} {
		writeOwnedArtifactFixture(t, filepath.Join(directory, name), content, 0600)
		if err := recordRsyslogArtifactProvenanceAtUsing(
			parent, uid, gid, name, content,
			func(directory *os.File) error { return directory.Sync() },
		); err != nil {
			t.Fatal(err)
		}
	}
	activationCalls := 0
	err := disableSIEMRsyslogForwarderAtUsing(
		parent,
		uid,
		gid,
		nil,
		defaultExactOwnedArtifactRemovalOptions(),
		func(changed bool) error {
			if !changed {
				t.Fatal("SIEM disable did not request changed-state activation")
			}
			activationCalls++
			return nil
		},
		allowTestRsyslogMutation,
	)
	if err != nil {
		t.Fatalf("disable exact SIEM forwarder: %v", err)
	}
	if activationCalls != 1 {
		t.Fatalf("SIEM disable activation calls = %d", activationCalls)
	}
	if _, err := os.Lstat(filepath.Join(directory, rsyslogSIEMConfigName)); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("disabled SIEM forwarder remains: %v", err)
	}
	if got, err := os.ReadFile(filepath.Join(directory, wafRsyslogConfigName)); err != nil || !bytes.Equal(got, waf) { // #nosec G304 -- fixed WAF name is beneath the private SIEM-disable fixture root
		t.Fatalf("WAF bridge changed during SIEM disable = %q, %v", got, err)
	}
	registry, err := readRsyslogProvenanceRegistryAtUsing(parent, uid, gid)
	if err != nil || !registry.exists || len(registry.records) != 1 {
		t.Fatalf("post-disable provenance = %#v, %v", registry, err)
	}
	if _, exists := registry.records[wafRsyslogConfigName]; !exists {
		t.Fatalf("post-disable provenance lost WAF record: %#v", registry.records)
	}
	if _, exists := registry.records[rsyslogSIEMConfigName]; exists {
		t.Fatalf("post-disable provenance retained SIEM record: %#v", registry.records)
	}
}

func TestSIEMDisableServiceFailureRestoresForwarderAndKeepsProvenance_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	siem := []byte("managed SIEM bytes\n")
	writeOwnedArtifactFixture(t, filepath.Join(directory, rsyslogSIEMConfigName), siem, 0600)
	if err := recordRsyslogArtifactProvenanceAtUsing(
		parent, uid, gid, rsyslogSIEMConfigName, siem,
		func(directory *os.File) error { return directory.Sync() },
	); err != nil {
		t.Fatal(err)
	}
	sentinel := errors.New("synthetic rsyslog failure")
	activationCalls := 0
	err := disableSIEMRsyslogForwarderAtUsing(
		parent,
		uid,
		gid,
		nil,
		defaultExactOwnedArtifactRemovalOptions(),
		func(bool) error { activationCalls++; return sentinel },
		allowTestRsyslogMutation,
	)
	if err == nil || !errors.Is(err, sentinel) {
		t.Fatalf("SIEM disable service failure = %v", err)
	}
	if activationCalls != 2 {
		t.Fatalf("SIEM disable rollback activation calls = %d", activationCalls)
	}
	if got, readErr := os.ReadFile(filepath.Join(directory, rsyslogSIEMConfigName)); readErr != nil || !bytes.Equal(got, siem) { // #nosec G304 -- fixed SIEM name is beneath the private rollback fixture root
		t.Fatalf("SIEM forwarder rollback = %q, %v", got, readErr)
	}
	registry, readErr := readRsyslogProvenanceRegistryAtUsing(parent, uid, gid)
	if readErr != nil || !registry.exists {
		t.Fatalf("SIEM rollback provenance = %#v, %v", registry, readErr)
	}
	if _, exists := registry.records[rsyslogSIEMConfigName]; !exists {
		t.Fatalf("SIEM rollback provenance record missing: %#v", registry.records)
	}
}

func TestSIEMDisableRemovesExactUntrackedCurrentAndV4032Forwarders_SW2_PKG_001(t *testing.T) {
	current, err := renderSIEMRsyslogConfig("192.0.2.40", "514", "udp", "")
	if err != nil {
		t.Fatal(err)
	}
	legacy, err := renderLegacyV4032SIEMRsyslogConfig("192.0.2.40", "514", "udp", "")
	if err != nil {
		t.Fatal(err)
	}
	alternatives := [][]byte{[]byte(current), []byte(legacy)}
	for name, rendered := range map[string]string{
		"current action-only": current,
		"legacy v4.03.2":      legacy,
	} {
		t.Run(name, func(t *testing.T) {
			parent := t.TempDir()
			uid, gid := testOwnedParentIdentity(t, parent)
			directory := filepath.Join(parent, wafRsyslogDirectoryName)
			if err := os.Mkdir(directory, 0750); err != nil {
				t.Fatal(err)
			}
			path := filepath.Join(directory, rsyslogSIEMConfigName)
			writeOwnedArtifactFixture(t, path, []byte(rendered), 0600)
			activationCalls := 0
			err := disableSIEMRsyslogForwarderAtUsing(
				parent,
				uid,
				gid,
				alternatives,
				defaultExactOwnedArtifactRemovalOptions(),
				func(changed bool) error {
					if !changed {
						t.Fatal("untracked SIEM disable did not request changed-state activation")
					}
					activationCalls++
					return nil
				},
				allowTestRsyslogMutation,
			)
			if err != nil || activationCalls != 1 {
				t.Fatalf("untracked SIEM disable = calls %d, %v", activationCalls, err)
			}
			if _, statErr := os.Lstat(path); !errors.Is(statErr, os.ErrNotExist) {
				t.Fatalf("untracked SIEM forwarder remains: %v", statErr)
			}
			registry, readErr := readRsyslogProvenanceRegistryAtUsing(parent, uid, gid)
			if readErr != nil || registry.exists {
				t.Fatalf("untracked SIEM disable invented provenance = %#v, %v", registry, readErr)
			}
		})
	}
}

func TestSIEMDisablePreservesUntrackedNonGeneratedBytes_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	current, err := renderSIEMRsyslogConfig("192.0.2.40", "514", "udp", "")
	if err != nil {
		t.Fatal(err)
	}
	legacy, err := renderLegacyV4032SIEMRsyslogConfig("192.0.2.40", "514", "udp", "")
	if err != nil {
		t.Fatal(err)
	}
	operator := []byte("operator-owned SIEM bytes\n")
	path := filepath.Join(directory, rsyslogSIEMConfigName)
	writeOwnedArtifactFixture(t, path, operator, 0600)
	warnings := []string{}
	options := defaultExactOwnedArtifactRemovalOptions()
	options.warn = func(message string) { warnings = append(warnings, message) }
	activationCalls := 0
	err = disableSIEMRsyslogForwarderAtUsing(
		parent,
		uid,
		gid,
		[][]byte{[]byte(current), []byte(legacy)},
		options,
		func(bool) error { activationCalls++; return nil },
		allowTestRsyslogMutation,
	)
	if err == nil || !strings.Contains(err.Error(), "do not match the current or v4.03.2") {
		t.Fatalf("untracked operator SIEM disable error = %v", err)
	}
	if activationCalls != 0 {
		t.Fatalf("untracked operator SIEM triggered %d activations", activationCalls)
	}
	if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, operator) { // #nosec G304 -- path is confined to the private untracked SIEM fixture root
		t.Fatalf("untracked operator SIEM bytes = %q, %v", got, readErr)
	}
	if len(warnings) != 1 {
		t.Fatalf("untracked operator SIEM warnings = %v", warnings)
	}
}

func TestSIEMProducerMigratesV4032ConfigAndRecordsCurrentProvenanceBeforeWAF_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	legacy, err := renderLegacyV4032SIEMRsyslogConfig("192.0.2.40", "514", "udp", "")
	if err != nil {
		t.Fatal(err)
	}
	current, err := renderSIEMRsyslogConfig("192.0.2.40", "514", "udp", "")
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(directory, rsyslogSIEMConfigName)
	writeOwnedArtifactFixture(t, path, []byte(legacy), 0600)
	record := func(directory *os.File, name string, content []byte) error {
		return recordRsyslogArtifactProvenanceInDirectoryUsing(
			directory,
			uid,
			gid,
			name,
			content,
			func(directory *os.File) error { return directory.Sync() },
		)
	}
	activationCalls := 0
	err = reconcileRsyslogArtifactWithProvenanceAtUsing(
		parent,
		uid,
		gid,
		rsyslogSIEMConfigName,
		"SIEM forwarder",
		[]byte(current),
		func(changed bool) error {
			if !changed {
				t.Fatal("legacy SIEM migration was not reported as changed")
			}
			activationCalls++
			return nil
		},
		record,
		allowTestRsyslogMutation,
	)
	if err != nil || activationCalls != 1 {
		t.Fatalf("migrate v4.03.2 SIEM config = calls %d, %v", activationCalls, err)
	}
	if got, readErr := os.ReadFile(path); readErr != nil || string(got) != current { // #nosec G304 -- path is confined to the private SIEM migration fixture root
		t.Fatalf("migrated SIEM config = %q, %v", got, readErr)
	}
	registry, readErr := readRsyslogProvenanceRegistryAtUsing(parent, uid, gid)
	if readErr != nil || !registry.exists {
		t.Fatalf("migrated SIEM provenance = %#v, %v", registry, readErr)
	}
	recorded, exists := registry.records[rsyslogSIEMConfigName]
	if !exists || recorded.size != int64(len(current)) || recorded.digest != sha256.Sum256([]byte(current)) {
		t.Fatalf("migrated SIEM provenance record = %#v", recorded)
	}
}

func TestRsyslogProducerRollsBackVisibleConfigWhenProvenanceFails_SW2_PKG_001(t *testing.T) {
	tests := []struct {
		name       string
		oldContent []byte
	}{
		{name: "historical config", oldContent: []byte("historical WAF bytes\n")},
		{name: "first publication"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			parent := t.TempDir()
			uid, gid := testOwnedParentIdentity(t, parent)
			if test.oldContent != nil {
				if _, err := reconcileRsyslogArtifactAtUsing(
					parent, wafRsyslogConfigName, uid, gid, test.oldContent, nil,
					func(directory *os.File) error { return directory.Sync() },
				); err != nil {
					t.Fatal(err)
				}
				if err := recordRsyslogArtifactProvenanceAtUsing(
					parent, uid, gid, wafRsyslogConfigName, test.oldContent,
					func(directory *os.File) error { return directory.Sync() },
				); err != nil {
					t.Fatal(err)
				}
			}
			sentinel := errors.New("synthetic provenance failure")
			activationCalls := 0
			newContent := []byte("new WAF bytes\n")
			err := reconcileRsyslogArtifactWithProvenanceAtUsing(
				parent,
				uid,
				gid,
				wafRsyslogConfigName,
				"WAF bridge",
				newContent,
				func(bool) error { activationCalls++; return nil },
				func(*os.File, string, []byte) error { return sentinel },
				allowTestRsyslogMutation,
			)
			if err == nil || !errors.Is(err, sentinel) {
				t.Fatalf("producer provenance failure = %v", err)
			}
			if activationCalls != 0 {
				t.Fatalf("producer activated unprovenanced config %d times", activationCalls)
			}
			path := filepath.Join(parent, wafRsyslogDirectoryName, wafRsyslogConfigName)
			if test.oldContent == nil {
				if _, statErr := os.Lstat(path); !errors.Is(statErr, os.ErrNotExist) {
					t.Fatalf("first unprovenanced publication remains: %v", statErr)
				}
				return
			}
			if got, readErr := os.ReadFile(path); readErr != nil || !bytes.Equal(got, test.oldContent) { // #nosec G304 -- path is confined to the private producer-rollback fixture root
				t.Fatalf("historical config rollback = %q, %v", got, readErr)
			}
			registry, readErr := readRsyslogProvenanceRegistryAtUsing(parent, uid, gid)
			if readErr != nil || registry.records[wafRsyslogConfigName].digest != sha256.Sum256(test.oldContent) {
				t.Fatalf("historical provenance rollback = %#v, %v", registry, readErr)
			}
		})
	}
}

func TestRsyslogProducerRecordsVisibleConfigBeforeActivation_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	oldContent := []byte("historical WAF bytes\n")
	newContent := []byte("new WAF bytes\n")
	if _, err := reconcileRsyslogArtifactAtUsing(
		parent, wafRsyslogConfigName, uid, gid, oldContent, nil,
		func(directory *os.File) error { return directory.Sync() },
	); err != nil {
		t.Fatal(err)
	}
	if err := recordRsyslogArtifactProvenanceAtUsing(
		parent, uid, gid, wafRsyslogConfigName, oldContent,
		func(directory *os.File) error { return directory.Sync() },
	); err != nil {
		t.Fatal(err)
	}
	record := func(directory *os.File, name string, content []byte) error {
		return recordRsyslogArtifactProvenanceInDirectoryUsing(
			directory, uid, gid, name, content,
			func(directory *os.File) error { return directory.Sync() },
		)
	}
	activationCalls := 0
	err := reconcileRsyslogArtifactWithProvenanceAtUsing(
		parent,
		uid,
		gid,
		wafRsyslogConfigName,
		"WAF bridge",
		newContent,
		func(changed bool) error {
			activationCalls++
			if !changed {
				t.Fatal("historical config change was not reported")
			}
			visible, readErr := os.ReadFile(filepath.Join(parent, wafRsyslogDirectoryName, wafRsyslogConfigName)) // #nosec G304 -- fixed WAF path is beneath the private publication fixture root
			registry, registryErr := readRsyslogProvenanceRegistryAtUsing(parent, uid, gid)
			if readErr != nil || registryErr != nil || !bytes.Equal(visible, newContent) ||
				registry.records[wafRsyslogConfigName].digest != sha256.Sum256(newContent) {
				t.Fatalf("pre-activation config/provenance = %q/%#v, %v/%v", visible, registry, readErr, registryErr)
			}
			return nil
		},
		record,
		allowTestRsyslogMutation,
	)
	if err != nil || activationCalls != 1 {
		t.Fatalf("provenanced producer activation = %d, %v", activationCalls, err)
	}
}

func TestRsyslogProducerAndPackageRemovalShareWholeTransactionLock_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	waf := []byte("managed WAF bytes\n")
	siem := []byte("managed SIEM bytes\n")
	for name, content := range map[string][]byte{
		wafRsyslogConfigName:  waf,
		rsyslogSIEMConfigName: siem,
	} {
		if _, err := reconcileRsyslogArtifactAtUsing(
			parent, name, uid, gid, content, nil,
			func(directory *os.File) error { return directory.Sync() },
		); err != nil {
			t.Fatal(err)
		}
		if err := recordRsyslogArtifactProvenanceAtUsing(
			parent, uid, gid, name, content,
			func(directory *os.File) error { return directory.Sync() },
		); err != nil {
			t.Fatal(err)
		}
	}

	publisherHolding := make(chan struct{})
	releasePublisher := make(chan struct{})
	publisherDone := make(chan error, 1)
	go func() {
		publisherDone <- reconcileRsyslogArtifactWithProvenanceAtUsing(
			parent,
			uid,
			gid,
			wafRsyslogConfigName,
			"WAF bridge",
			waf,
			func(bool) error {
				close(publisherHolding)
				<-releasePublisher
				return nil
			},
			func(directory *os.File, name string, content []byte) error {
				return recordRsyslogArtifactProvenanceInDirectoryUsing(
					directory, uid, gid, name, content,
					func(directory *os.File) error { return directory.Sync() },
				)
			},
			allowTestRsyslogMutation,
		)
	}()
	select {
	case <-publisherHolding:
	case <-time.After(5 * time.Second):
		t.Fatal("publisher did not reach the activation barrier")
	}

	directoryPath := filepath.Join(parent, wafRsyslogDirectoryName)
	probeFD, err := unix.Open(directoryPath, unix.O_RDONLY|unix.O_DIRECTORY|unix.O_NOFOLLOW|unix.O_CLOEXEC, 0)
	if err != nil {
		t.Fatal(err)
	}
	lockErr := unix.Flock(probeFD, unix.LOCK_EX|unix.LOCK_NB)
	_ = unix.Close(probeFD)
	if !errors.Is(lockErr, unix.EWOULDBLOCK) {
		t.Fatalf("publisher did not hold the directory transaction lock: %v", lockErr)
	}

	purgeStarted := make(chan struct{})
	purgeDone := make(chan error, 1)
	go func() {
		close(purgeStarted)
		purgeDone <- removeOwnedGeneratedArtifactsForPackageRemovalAtUsing(
			config.NewFailSafeConfig(),
			parent,
			uid,
			gid,
			defaultExactOwnedArtifactRemovalOptions(),
			func(bool) error { return nil },
		)
	}()
	<-purgeStarted
	select {
	case err := <-purgeDone:
		t.Fatalf("purge bypassed producer transaction lock: %v", err)
	default:
	}
	close(releasePublisher)
	select {
	case err := <-publisherDone:
		if err != nil {
			t.Fatalf("publisher transaction: %v", err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("publisher transaction did not finish")
	}
	select {
	case err := <-purgeDone:
		if err != nil {
			t.Fatalf("serialized purge transaction: %v", err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("serialized purge transaction did not finish")
	}
	for _, name := range []string{wafRsyslogConfigName, rsyslogSIEMConfigName, rsyslogProvenanceName} {
		if _, err := os.Lstat(filepath.Join(directoryPath, name)); !errors.Is(err, os.ErrNotExist) {
			t.Fatalf("serialized transaction left %s: %v", name, err)
		}
	}
}

func TestBlockedStaleRsyslogProducerRefusesAfterPackageRemovalTransaction_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	waf := []byte("managed WAF bytes\n")
	siem := []byte("managed SIEM bytes\n")
	for name, content := range map[string][]byte{
		wafRsyslogConfigName:  waf,
		rsyslogSIEMConfigName: siem,
	} {
		if _, err := reconcileRsyslogArtifactAtUsing(
			parent, name, uid, gid, content, nil,
			func(directory *os.File) error { return directory.Sync() },
		); err != nil {
			t.Fatal(err)
		}
		if err := recordRsyslogArtifactProvenanceAtUsing(
			parent, uid, gid, name, content,
			func(directory *os.File) error { return directory.Sync() },
		); err != nil {
			t.Fatal(err)
		}
	}

	purgeHolding := make(chan struct{})
	releasePurge := make(chan struct{})
	purgeDone := make(chan error, 1)
	activationCalls := 0
	go func() {
		purgeDone <- removeOwnedGeneratedArtifactsForPackageRemovalAtUsing(
			config.NewFailSafeConfig(),
			parent,
			uid,
			gid,
			defaultExactOwnedArtifactRemovalOptions(),
			func(bool) error {
				activationCalls++
				if activationCalls == 1 {
					close(purgeHolding)
					<-releasePurge
				}
				return nil
			},
		)
	}()
	select {
	case <-purgeHolding:
	case <-time.After(5 * time.Second):
		t.Fatal("purge did not reach its first activation barrier")
	}

	producerPreflight := make(chan struct{})
	publisherDone := make(chan error, 1)
	go func() {
		publisherDone <- reconcileRsyslogArtifactWithProvenanceAtUsing(
			parent,
			uid,
			gid,
			wafRsyslogConfigName,
			"WAF bridge",
			waf,
			func(bool) error { return nil },
			func(directory *os.File, name string, content []byte) error {
				return recordRsyslogArtifactProvenanceInDirectoryUsing(
					directory, uid, gid, name, content,
					func(directory *os.File) error { return directory.Sync() },
				)
			},
			func() error {
				close(producerPreflight)
				return requireRsyslogMutationWithoutRemovalBarrierUsing(
					func() (bool, error) { return true, nil },
				)
			},
		)
	}()
	select {
	case <-producerPreflight:
		t.Fatal("stale producer ran its preflight while purge still held the transaction lock")
	default:
	}
	close(releasePurge)
	select {
	case err := <-purgeDone:
		if err != nil {
			t.Fatalf("purge transaction: %v", err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("purge transaction did not finish")
	}
	select {
	case <-producerPreflight:
	case <-time.After(5 * time.Second):
		t.Fatal("stale producer did not recheck the removal barrier after acquiring the lock")
	}
	select {
	case err := <-publisherDone:
		if err == nil || !strings.Contains(err.Error(), "durable removal barrier is present") {
			t.Fatalf("stale producer result = %v", err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("stale producer did not finish")
	}
	directoryPath := filepath.Join(parent, wafRsyslogDirectoryName)
	for _, name := range []string{wafRsyslogConfigName, rsyslogSIEMConfigName, rsyslogProvenanceName} {
		if _, err := os.Lstat(filepath.Join(directoryPath, name)); !errors.Is(err, os.ErrNotExist) {
			t.Fatalf("stale producer left %s after purge: %v", name, err)
		}
	}
}

func TestGeneratedRsyslogRemovalBlocksMalformedProvenanceAndPreservesArtifacts_SW2_PKG_001(t *testing.T) {
	parent := t.TempDir()
	uid, gid := testOwnedParentIdentity(t, parent)
	directory := filepath.Join(parent, wafRsyslogDirectoryName)
	if err := os.Mkdir(directory, 0750); err != nil {
		t.Fatal(err)
	}
	waf := []byte("managed WAF bytes\n")
	writeOwnedArtifactFixture(t, filepath.Join(directory, wafRsyslogConfigName), waf, 0600)
	writeOwnedArtifactFixture(t, filepath.Join(directory, rsyslogProvenanceName), []byte("tampered\n"), 0600)
	activationCalls := 0
	err := removeOwnedGeneratedArtifactsForPackageRemovalAtUsing(
		config.NewFailSafeConfig(),
		parent,
		uid,
		gid,
		defaultExactOwnedArtifactRemovalOptions(),
		func(bool) error { activationCalls++; return nil },
	)
	if err == nil || !strings.Contains(err.Error(), "provenance") {
		t.Fatalf("malformed provenance cleanup error = %v", err)
	}
	if activationCalls != 0 {
		t.Fatalf("malformed provenance triggered %d activations", activationCalls)
	}
	for _, name := range []string{wafRsyslogConfigName, rsyslogProvenanceName} {
		if _, statErr := os.Lstat(filepath.Join(directory, name)); statErr != nil {
			t.Fatalf("malformed provenance did not preserve %s: %v", name, statErr)
		}
	}
}

func TestSIEMRsyslogPublicationRefusesSymlinkedPaths_SW2_PKG_001(t *testing.T) {
	t.Run("directory", func(t *testing.T) {
		parent := t.TempDir()
		uid, gid := testOwnedParentIdentity(t, parent)
		outside := t.TempDir()
		if err := os.Symlink(outside, filepath.Join(parent, wafRsyslogDirectoryName)); err != nil {
			t.Fatal(err)
		}
		_, err := reconcileSIEMRsyslogConfigAtUsing(
			parent, uid, gid, []byte("managed SIEM bytes\n"),
			func(directory *os.File) error { return directory.Sync() },
		)
		if err == nil {
			t.Fatal("symlinked rsyslog directory was accepted")
		}
	})
	t.Run("canonical file", func(t *testing.T) {
		parent := t.TempDir()
		uid, gid := testOwnedParentIdentity(t, parent)
		directory := filepath.Join(parent, wafRsyslogDirectoryName)
		if err := os.Mkdir(directory, 0750); err != nil {
			t.Fatal(err)
		}
		operator := []byte("operator target\n")
		target := filepath.Join(parent, "operator-target")
		writeOwnedArtifactFixture(t, target, operator, 0600)
		if err := os.Symlink(target, filepath.Join(directory, rsyslogSIEMConfigName)); err != nil {
			t.Fatal(err)
		}
		_, err := reconcileSIEMRsyslogConfigAtUsing(
			parent, uid, gid, []byte("managed SIEM bytes\n"),
			func(directory *os.File) error { return directory.Sync() },
		)
		if err == nil {
			t.Fatal("symlinked SIEM canonical was accepted")
		}
		if got, readErr := os.ReadFile(target); readErr != nil || !bytes.Equal(got, operator) { // #nosec G304 -- target is confined to the private SIEM symlink-adversary fixture root
			t.Fatalf("SIEM symlink target = %q, %v", got, readErr)
		}
	})
}
