"""Reject unsafe archives and network-policy drift in restoration evidence."""
import io
import tarfile
import unittest

from scripts.ci import release_ivv_v4104_restoration as subject


def archive(name='proof.txt', kind=tarfile.REGTYPE, data=b'proof', duplicate=False):
    output = io.BytesIO()
    with tarfile.open(fileobj=output, mode='w:gz') as stream:
        for _ in range(2 if duplicate else 1):
            member = tarfile.TarInfo(name)
            member.type = kind
            member.size = len(data) if kind == tarfile.REGTYPE else 0
            member.linkname = '/etc/passwd' if kind == tarfile.SYMTYPE else ''
            stream.addfile(member, io.BytesIO(data) if member.size else None)
    return output.getvalue()


class RestorationTests(unittest.TestCase):
    def test_archive_does_not_extract_links_or_unbounded_members(self):
        self.assertEqual(subject.archive_files(archive()), {'proof.txt': b'proof'})
        for wire in (archive('../escape'), archive('/absolute'),
                     archive(kind=tarfile.SYMTYPE), archive(duplicate=True)):
            with self.assertRaises(subject.frozen.PlanError):
                subject.archive_files(wire)
        with self.assertRaises(subject.frozen.PlanError):
            subject.archive_files(archive(), maximum=4)

    def test_provider_regeneration_cannot_hide_address_or_route_changes(self):
        before = b'# Generated by Linode Network Helper\n# old\n[ipv4]\ndns=192.0.2.53;\nmethod=manual\n[ipv6]\nmethod=auto\n'
        after = before.replace(b'# old', b'# new').replace(b'192.0.2.53', b'192.0.2.54')
        self.assertEqual(subject.provider_changes(before, after),
                         ['provider_timestamp', 'provider_ipv4_dns'])
        for bad in (after.replace(b'method=manual', b'method=auto'),
                    after.replace(b'method=auto', b'method=disabled'),
                    after.replace(b'192.0.2.54', b'2001:db8::53'),
                    after + b'address1=192.0.2.10/24\n'):
            with self.assertRaises((subject.frozen.PlanError, ValueError)):
                subject.provider_changes(before, bad)
        with self.assertRaises(subject.frozen.PlanError):
            subject.provider_changes(before, after, original=True)
        self.assertEqual(subject.provider_changes(before, before, original=True), [])


if __name__ == '__main__':
    unittest.main()
