"""Verify both final restored baselines without exporting private host evidence."""
from __future__ import annotations

import base64
import io
import ipaddress
import tarfile

try:
    from scripts.ci import release_ivv_v4104_evidence as proof
except ModuleNotFoundError:
    import release_ivv_v4104_evidence as proof

equal, require, frozen = proof.equal, proof.require, proof.frozen


def archive_files(wire: bytes, maximum: int = 16 * 1024 * 1024) -> dict[str, bytes]:
    result, total, seen = {}, 0, set()
    with tarfile.open(fileobj=io.BytesIO(wire), mode='r:gz') as archive:
        for member in archive:
            name = proof.relative(member.name)
            require(name not in seen and len(seen) < 100 and member.size >= 0 and
                    (member.isfile() or (member.isdir() and member.size == 0)),
                    'unsafe restored evidence archive')
            seen.add(name)
            if member.isdir():
                continue
            total += member.size
            require(total <= maximum and len(result) < 100, 'restored archive exceeds bound')
            result[name] = archive.extractfile(member).read(member.size + 1)
            equal(len(result[name]), member.size, 'truncated restoration evidence')
    return result


def provider_changes(before: bytes, after: bytes, original: bool = False) -> list[str]:
    if original:
        equal(before, after, 'original provider profile was changed')
        return []
    left, right = before.decode().splitlines(), after.decode().splitlines()
    require(len(left) == len(right) and left and
            left[0] == right[0] == '# Generated by Linode Network Helper',
            'provider profile shape changed')
    fields = []
    for index, (a, b) in enumerate(zip(left, right)):
        if a == b:
            continue
        if index == 1:
            require(a.startswith('# ') and b.startswith('# '), 'provider header changed')
            fields.append('provider_timestamp')
        else:
            require(a.startswith('dns=') and b.startswith('dns=') and
                    next((line for line in reversed(right[:index]) if line.startswith('[')), '') == '[ipv4]',
                    'unreviewed provider network policy change')
            values = b[4:].split(';')
            require(any(values) and all(ipaddress.ip_address(value).version == 4
                    for value in values if value), 'invalid provider DNS regeneration')
            fields.append('provider_ipv4_dns')
    return fields


def verify_debian(group: proof.Group, native: proof.Group) -> None:
    receipt = group.document('verified-receipt.json')
    equal(receipt['returncode'], 0, 'restored Debian verifier failed')
    equal(receipt['read_only'], True, 'restored inspection changed the host')
    for field, name in [('source', 'verify-hardening.py'), ('stdout', 'verified.stdout'),
                        ('stderr', 'verified.stderr')]:
        equal(frozen.digest(group.data(name)), receipt[field + '_sha256'],
              'restored Debian capture differs')
    result = group.document('verified.stdout')
    equal(result['all_passed'], True, 'Debian baseline is not restored')
    equal(result['total'], 137, 'original hardening coverage changed')
    equal(result['passed'], 137, 'an original hardening control is missing')
    checks = result['checks']
    require(len(checks) == 137 and len({row['check'] for row in checks}) == 137 and
            all(row['passed'] is True for row in checks), 'hardening verdict hides a failure')
    extra = result['post_restore_checks']
    require(len(extra) == 19 and all(value is True for value in extra.values()),
            'final restored baseline contains test or product artifacts')
    verdict = group.document('RESTORATION-VERDICT.json')
    equal(verdict['status'], 'PASS_RESTORED_INITIAL_HARDENED_BASELINE', 'restoration incomplete')
    equal(verdict['final_restoration'], True, 'earlier restoration substituted')
    equal(verdict['release_acceptance'], False, 'restoration cannot grant release acceptance')
    equal(verdict['post_restore_checks'], extra, 'restoration checks were relabeled')
    equal(verdict['boot_id'], result['boot_id'], 'restoration boot differs')
    equal(verdict['proof_sha256'], receipt['stdout_sha256'], 'restored proof was replaced')
    prior = native.document('standalone-removed-r2-verify02-evidence-final/result.json')
    require(result['boot_id'] != prior['boot_id'], 'final snapshot restoration did not reboot')
    repair = group.document('restore-history-attributes-receipt.json')
    equal(frozen.digest(group.data('restore-history-attributes.stdout')), repair['stdout_sha256'],
          'history attribute repair capture differs')
    equal(group.document('restore-history-attributes.stdout'), repair['result'], 'repair result differs')
    equal(repair['result']['status'], 'PASS', 'history attribute repair is incomplete')
    require(len(repair['result']['records']) == 2 and all(
        row['content_unchanged'] is True and row['identity_unchanged'] is True and
        row['flags_before'].replace('-', '') == 'e' and
        row['flags_after'].replace('-', '') == 'ae'
        for row in repair['result']['records']), 'history repair exceeded attribute-only scope')


def verify_alma(group: proof.Group, native: proof.Group) -> None:
    verdict = group.document('RESTORATION-VERDICT.json')
    equal(verdict['status'], 'PASS_RESTORED_ENTRY_BASELINE_WITH_VERIFIED_PROVIDER_REGENERATION',
          'AlmaLinux final baseline is not restored')
    for field in ('final_restore', 'normal_boot_verified', 'transfer_copy_removed',
                  'all_non_network_files_exact', 'preboot_network_files_exact'):
        equal(verdict[field], True, 'AlmaLinux restoration is incomplete')
    equal(verdict['release_acceptance'], False, 'restoration cannot grant acceptance')
    original = group.document('baseline.json')
    observed = group.document('strict-observation.json')
    strict = group.document('strict-verdict.json')
    equal([row['name'] for row in strict['checks'] if not row['passed']],
          ['exact_original_policy_files'], 'unreviewed restored baseline failure')
    equal(len(strict['checks']), 20, 'restored baseline coverage changed')
    archive_wire = group.data('proof.tar.gz')
    equal(frozen.digest(archive_wire), verdict['repair_archive_sha256'], 'repair archive differs')
    files = archive_files(archive_wire)
    equal(files['result.txt'], b'APPLY_RC=0\nVERIFY_RC=0\nVERIFY_LINES=0\nSELINUX=enforcing\n',
          'SELinux repair did not verify')
    equal(files['labels-verification.log'], b'', 'SELinux labels remain incorrect')
    before = archive_files(files['preboot-network.tar.gz'])
    current = group.document('current-state.json')
    changes = {}
    for name, encoded in current['files_base64'].items():
        proof.relative(name)
        require('/' not in name, 'unsafe provider profile name')
        path = '/etc/NetworkManager/system-connections/' + name
        first = before['etc/NetworkManager/system-connections/' + name]
        equal(frozen.digest(first), original['files'][path]['sha256'], 'preboot profile changed')
        changes[name] = provider_changes(first, base64.b64decode(encoded, validate=True),
                                        name.endswith('.linode-orig'))
        for key in ('mode', 'uid', 'gid', 'nlink'):
            equal(observed['files'][path][key], original['files'][path][key],
                  'provider profile metadata changed')
    equal(len(changes), 3, 'provider profile inventory differs')
    equal(changes, verdict['provider_profile_changes'], 'provider changes exceed reviewed scope')
    for name, row in original['files'].items():
        if not name.startswith('/etc/NetworkManager/system-connections/'):
            equal(observed['files'].get(name), row, 'original administrator policy changed')
    final = group.document('final-remote.json')
    equal(final['transfer_copy_removed'], True, 'temporary transfer archive remains')
    commands = final['commands']
    require(all(row['rc'] == 0 and row['err'] == '' for row in commands), 'final restored command failed')
    outputs = {tuple(row['argv']): row['out'] for row in commands}
    equal(len(outputs), len(commands), 'duplicate final command')
    equal(outputs[('getenforce',)], 'Enforcing\n', 'SELinux enforcement is not restored')
    equal(outputs[('systemctl', '--failed', '--no-legend', '--no-pager')], '', 'restored service failed')
    equal(outputs[('cat', '/proc/sys/kernel/random/boot_id')].strip(), verdict['boot_id'],
          'normal restored boot differs')
    previous = native.document('opt-in-removed-reboot01/VERDICT.json')
    require(verdict['boot_id'] != previous['after_boot'], 'final snapshot boot was not observed')
