package platformpaths

import (
	"errors"
	"strconv"
	"strings"
)

var ErrUnterminatedOperatorCronRecord = errors.New("cannot add a managed cron record after an unterminated operator record")

// ReconcileCronRecords removes only records owned by the selected predicate.
// Every surviving record retains its original bytes and LF terminator. When a
// replacement is required, an unterminated final operator record is rejected
// because appending would modify its bytes and prepending could change cron
// environment-variable semantics.
func ReconcileCronRecords(content string, owned func(string) bool, replacement string) (string, error) {
	var filtered strings.Builder
	for len(content) > 0 {
		line := content
		terminated := false
		if lineEnd := strings.IndexByte(content, '\n'); lineEnd >= 0 {
			line = content[:lineEnd]
			content = content[lineEnd+1:]
			terminated = true
		} else {
			content = ""
		}
		if !owned(line) {
			filtered.WriteString(line)
			if terminated {
				filtered.WriteByte('\n')
			}
		}
	}

	result := filtered.String()
	if replacement == "" {
		return result, nil
	}
	if result != "" && !strings.HasSuffix(result, "\n") {
		return "", ErrUnterminatedOperatorCronRecord
	}
	return result + replacement + "\n", nil
}

func managedCronFields(line string) ([]string, bool) {
	fields := strings.Fields(line)
	if len(fields) != 9 || fields[1] != "*" || fields[2] != "*" ||
		fields[3] != "*" || fields[4] != "*" ||
		fields[7] != ">/dev/null" || fields[8] != "2>&1" {
		return nil, false
	}
	if line != strings.Join(fields, " ") {
		return nil, false
	}
	for _, path := range managedCronCLIPaths {
		if fields[5] == path {
			return fields, true
		}
	}
	return nil, false
}

// IsManagedHACronLine reports whether line is the exact HA synchronization
// entry generated by SysWarden.
func IsManagedHACronLine(line string) bool {
	fields, managed := managedCronFields(line)
	return managed && fields[0] == "*/30" && fields[6] == "ha-sync"
}

// IsManagedFeedCronLine reports whether line is an exact threat-feed update
// entry generated by SysWarden.
func IsManagedFeedCronLine(line string) bool {
	fields, managed := managedCronFields(line)
	if !managed || fields[6] != "update-feeds" {
		return false
	}
	minute, err := strconv.Atoi(fields[0])
	return err == nil && strconv.Itoa(minute) == fields[0] && minute >= 1 && minute <= 59
}

// IsManagedCronLine reports whether line is one of the two exact root cron
// entries generated by SysWarden. It deliberately rejects other commands that
// merely contain the binary name.
func IsManagedCronLine(line string) bool {
	return IsManagedHACronLine(line) || IsManagedFeedCronLine(line)
}
