package platformpaths

import (
	"strconv"
	"strings"
)

// IsManagedCronLine reports whether line is one of the two exact root cron
// entries generated by SysWarden. It deliberately rejects other commands that
// merely contain the binary name.
func IsManagedCronLine(line string) bool {
	fields := strings.Fields(line)
	if len(fields) != 9 || fields[1] != "*" || fields[2] != "*" ||
		fields[3] != "*" || fields[4] != "*" ||
		fields[7] != ">/dev/null" || fields[8] != "2>&1" {
		return false
	}
	managedCLI := false
	for _, path := range managedCronCLIPaths {
		if fields[5] == path {
			managedCLI = true
			break
		}
	}
	if !managedCLI {
		return false
	}
	if fields[0] == "*/30" && fields[6] == "ha-sync" {
		return true
	}
	minute, err := strconv.Atoi(fields[0])
	return err == nil && strconv.Itoa(minute) == fields[0] && minute >= 1 &&
		minute <= 59 && fields[6] == "update-feeds"
}
