//go:build linux

package firewall

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"fmt"
	"io/fs"
	"path/filepath"
	"strings"
)

const asnPolicyPinHeader = "SYSWARDEN_ASN_POLICY_V1\n"
const maximumPinnedASNBytes = 8 << 20
const maximumPinnedASNPrefixes = 100000

// ASN policy pins are explicit local operator approval of two immutable files.
// They are never generated by package installation or by a network downloader.
// A pin does not authenticate an ASN publisher or authorize subsequent refreshes.
func configuredASNPolicyPins(directory, base string) (string, string, error) {
	target := approvedListFile{directory: directory, name: base + ".policy-pin"}
	root, err := openListDirectory(target, false)
	if errors.Is(err, fs.ErrNotExist) {
		return "", "", nil
	}
	if err != nil {
		return "", "", fmt.Errorf("inspect ASN policy pin directory: %w", err)
	}
	defer func() { _ = root.Close() }()
	if _, err := root.Lstat(target.name); errors.Is(err, fs.ErrNotExist) {
		return "", "", nil
	} else if err != nil {
		return "", "", fmt.Errorf("inspect ASN policy pin: %w", err)
	}
	content, err := readPrivateRootedNFTFile(filepath.Join(directory, target.name), 256)
	if err != nil {
		return "", "", fmt.Errorf("read explicit ASN policy pin: %w", err)
	}
	lines := strings.Split(string(content), "\n")
	if len(lines) != 5 || lines[0]+"\n" != asnPolicyPinHeader || lines[4] != "" ||
		lines[1] != "list_base="+base || !strings.HasPrefix(lines[2], "ipv4_sha256=") || !strings.HasPrefix(lines[3], "ipv6_sha256=") {
		return "", "", fmt.Errorf("ASN policy pin must contain exactly the version header, selected list base and both ordered SHA-256 digests")
	}
	ipv4 := strings.TrimPrefix(lines[2], "ipv4_sha256=")
	ipv6 := strings.TrimPrefix(lines[3], "ipv6_sha256=")
	if err := validateNFTPersistentDigest(ipv4); err != nil {
		return "", "", fmt.Errorf("invalid IPv4 ASN policy pin: %w", err)
	}
	if err := validateNFTPersistentDigest(ipv6); err != nil {
		return "", "", fmt.Errorf("invalid IPv6 ASN policy pin: %w", err)
	}
	// Reject a partial or stale pair before constructing either source. Each
	// source is checked again against its pin when its actual bytes are parsed.
	for index, digest := range []string{ipv4, ipv6} {
		path := filepath.Join(directory, fmt.Sprintf("%s.ipv%d", base, 4+index*2))
		if _, err := readPinnedASNPolicy(path, digest); err != nil {
			return "", "", err
		}
	}
	again, err := readPrivateRootedNFTFile(filepath.Join(directory, target.name), 256)
	if err != nil || !bytes.Equal(content, again) {
		return "", "", fmt.Errorf("ASN policy pin changed while reading the approved pair")
	}
	return ipv4, ipv6, nil
}

func readPinnedASNPolicy(path, digest string) ([]byte, error) {
	if err := validateNFTPersistentDigest(digest); err != nil {
		return nil, err
	}
	content, err := readPrivateRootedNFTFile(path, maximumPinnedASNBytes)
	if err != nil {
		return nil, fmt.Errorf("read operator-pinned ASN list %s: %w", filepath.Base(path), err)
	}
	if actual := fmt.Sprintf("%x", sha256.Sum256(content)); actual != digest {
		return nil, fmt.Errorf("operator-pinned ASN list %s changed; explicit approval of the exact pair is required", filepath.Base(path))
	}
	return content, nil
}

func canonicalPinnedASNNetwork(value string, wantIPv6 bool) (string, bool, error) {
	// Operator-approved ASN routes can legitimately be wider than the generic
	// list floor. Keep the same canonical, family and public-space constraints
	// used for authenticated country routes, including rejection of /0.
	prefix, err := canonicalAuthenticatedGeoIPPrefix(value, wantIPv6)
	if err != nil {
		return "", false, fmt.Errorf("invalid operator-pinned ASN route: %w", err)
	}
	return prefix.String(), prefix.Addr().Is4(), nil
}
