//go:build linux

package firewall

import (
	"bytes"
	"context"
	"encoding/json"
	"reflect"
	"strconv"
	"strings"
	"testing"

	"syswarden-cli/config"
)

func legacyIPTablesFixture(t *testing.T, lines []string, handles []uint64) ([]byte, []byte) {
	t.Helper()
	if len(lines) != len(handles) {
		t.Fatal("fixture handle count mismatch")
	}
	entries := []any{
		map[string]any{"table": map[string]any{"family": "ip", "name": "filter", "handle": 41}},
		map[string]any{"chain": map[string]any{"family": "ip", "table": "filter", "name": "INPUT", "handle": 42, "type": "filter", "hook": "input", "prio": 0, "policy": "accept"}},
	}
	for index, line := range lines {
		expressions, err := legacyIPTablesGeneratedExpression(line)
		if err != nil {
			t.Fatal(err)
		}
		entries = append(entries, map[string]any{"rule": map[string]any{"family": "ip", "table": "filter", "chain": "INPUT", "handle": handles[index], "expr": expressions}})
	}
	nft, err := json.Marshal(map[string]any{"nftables": entries})
	if err != nil {
		t.Fatal(err)
	}
	save := "# Generated by synthetic fixture\n*filter\n:INPUT ACCEPT [0:0]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n"
	if len(lines) != 0 {
		save += strings.Join(lines, "\n") + "\n"
	}
	return nft, []byte(save + "COMMIT\n")
}

func legacyIPTablesTestObservation(t *testing.T, lines []string, handles []uint64) legacyIPTablesObservation {
	t.Helper()
	nft, save := legacyIPTablesFixture(t, lines, handles)
	result, err := observeLegacyIPTables(nft, save)
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func legacyIPTablesTestGeneration(t *testing.T) (legacyIPTablesObservation, legacyIPTablesObservation, legacyIPTablesInputs) {
	t.Helper()
	inputs := legacyIPTablesInputs{HAEnabled: true, HAPeerPort: "62026", LANSubnets: []string{"10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"}}
	block, err := legacyIPTablesExpectedBlock(inputs)
	if err != nil {
		t.Fatal(err)
	}
	// The administrator already has the same source rule and the same
	// comment-bearing port rule. Neither may be adopted by shape or comment.
	admin := []string{block[0], block[len(block)-1]}
	before := legacyIPTablesTestObservation(t, admin, []uint64{2, 3})
	lines := append(append(append([]string{}, block...), block...), admin...)
	var handles []uint64
	for index := 0; index < 2*len(block); index++ {
		handles = append(handles, uint64(100-index))
	}
	handles = append(handles, 2, 3)
	return before, legacyIPTablesTestObservation(t, lines, handles), inputs
}

func TestLegacyIPTablesPlanPreservesIdenticalAdministratorRules(t *testing.T) {
	before, generated, inputs := legacyIPTablesTestGeneration(t)
	plan, err := prepareLegacyIPTablesPlan(before, generated, generated, inputs, strings.Repeat("a", 64))
	if err != nil || len(plan.targets) != 18 {
		t.Fatal("complete repeated generation was not bounded", err)
	}
	wanted, err := legacyIPTablesObservationBytes(before)
	if err != nil || !bytes.Equal(plan.after, wanted) {
		t.Fatal("identical pre-existing administrator rules were not preserved", err)
	}
	for _, target := range plan.targets {
		if target.Handle == 2 || target.Handle == 3 {
			t.Fatal("administrator handle was selected")
		}
	}
	if !validLegacyRetirementDigest(plan.digest) {
		t.Fatal("review lacks a canonical digest")
	}
}

func TestLegacyIPTablesPlanPreservesLaterIdenticalAdministratorRule(t *testing.T) {
	before, generated, inputs := legacyIPTablesTestGeneration(t)
	lines := []string{generated.rules[0].line}
	handles := []uint64{500}
	for _, rule := range generated.rules {
		lines, handles = append(lines, rule.line), append(handles, rule.handle)
	}
	current := legacyIPTablesTestObservation(t, lines, handles)
	plan, err := prepareLegacyIPTablesPlan(before, generated, current, inputs, strings.Repeat("b", 64))
	if err != nil || len(plan.targets) != 18 || !bytes.Contains(plan.after, []byte(`"handle":500`)) {
		t.Fatal("later identical administrator rule was adopted", err)
	}
}

func TestLegacyIPTablesPlanRefusesIncompleteOrChangedLineage(t *testing.T) {
	for _, kind := range []string{"missing origins", "changed inputs", "partial generation", "partial current", "changed current expression", "changed original administrator rule", "reordered original administrator rules", "interleaved new rule", "unknown target metadata", "mismatched xt comment"} {
		t.Run(kind, func(t *testing.T) {
			before, generated, inputs := legacyIPTablesTestGeneration(t)
			_, current, _ := legacyIPTablesTestGeneration(t)
			origins := strings.Repeat("a", 64)
			switch kind {
			case "missing origins":
				origins = ""
			case "changed inputs":
				inputs.HAPeerPort = "62025"
			case "partial generation":
				generated.rules = generated.rules[1:]
			case "partial current":
				current.rules = current.rules[1:]
			case "changed current expression":
				current.rules[0].line = "-A INPUT -s 192.0.2.0/24 -j ACCEPT"
			case "changed original administrator rule":
				before.rules[0].line = "-A INPUT -s 192.0.2.0/24 -j ACCEPT"
			case "reordered original administrator rules":
				before.rules[0], before.rules[1] = before.rules[1], before.rules[0]
			case "interleaved new rule":
				generated.rules[0], generated.rules[18] = generated.rules[18], generated.rules[0]
			case "unknown target metadata":
				generated.rules[0].entry.(map[string]any)["rule"].(map[string]any)["comment"] = "administrator"
			case "mismatched xt comment":
				generated.rules[8].line = strings.ReplaceAll(generated.rules[8].line, "SYSWARDEN_CORE", "operator")
			}
			if _, err := prepareLegacyIPTablesPlan(before, generated, current, inputs, origins); err == nil {
				t.Fatal("ambiguous ownership was accepted")
			}
		})
	}
}

func TestLegacyIPTablesObservationCounterAndTextBoundaries(t *testing.T) {
	line := "-A INPUT -s 192.0.2.0/24 -j ACCEPT"
	nft, save := legacyIPTablesFixture(t, []string{line}, []uint64{9})
	first, err := observeLegacyIPTables(nft, save)
	if err != nil {
		t.Fatal(err)
	}
	changed := bytes.ReplaceAll(nft, []byte(`"packets":0`), []byte(`"packets":7`))
	changed = bytes.ReplaceAll(changed, []byte(`"bytes":0`), []byte(`"bytes":999`))
	second, err := observeLegacyIPTables(changed, save)
	if err != nil || !reflect.DeepEqual(first, second) {
		t.Fatal("ordinary traffic counters changed a structural observation", err)
	}
	for _, invalid := range [][]byte{nil, bytes.ReplaceAll(save, []byte("COMMIT"), nil), append(bytes.Clone(save), save...), bytes.ReplaceAll(save, []byte(line), []byte(line+"\n"+line)), append(bytes.Clone(save), 0), bytes.ReplaceAll(save, []byte("synthetic"), []byte{255})} {
		if _, err := observeLegacyIPTables(nft, invalid); err == nil {
			t.Fatal("incomplete or mismatched text observation accepted")
		}
	}
	for _, invalid := range [][]byte{[]byte(`{"nftables":[],"nftables":[]}`), bytes.ReplaceAll(nft, []byte(`"INPUT"`), []byte{34, 255, 34}), bytes.ReplaceAll(nft, []byte(`"packets":0`), []byte(`"packets":-1`)), bytes.ReplaceAll(nft, []byte(`"handle":9`), []byte(`"handle":0`))} {
		if _, err := observeLegacyIPTables(invalid, save); err == nil {
			t.Fatal("ambiguous kernel observation accepted")
		}
	}
}

func TestLegacyIPTablesPreflightRefusesBeforeMutation(t *testing.T) {
	before, generated, _ := legacyIPTablesTestGeneration(t)
	for _, observation := range []legacyIPTablesObservation{before, generated} {
		content, err := json.Marshal(map[string]any{"nftables": observation.entries})
		if err != nil {
			t.Fatal(err)
		}
		document, err := decodeNFTJSON(content)
		if err != nil || preflightLegacyIPTablesRules(document) == nil {
			t.Fatal("possible historical compatibility rules escaped the refusal", err)
		}
	}
	content, _ := legacyIPTablesFixture(t, []string{"-A INPUT -s 192.0.2.0/24 -j ACCEPT"}, []uint64{9})
	document, err := decodeNFTJSON(content)
	if err != nil || preflightLegacyIPTablesRules(document) != nil {
		t.Fatal("generic administrator source rule was classified by shape alone", err)
	}
	oldConfig, oldUID, oldFactory := config.GlobalConfig, firewallCleanupEffectiveUserID, uninstallNFTRunnerFactory
	t.Cleanup(func() {
		config.GlobalConfig, firewallCleanupEffectiveUserID, uninstallNFTRunnerFactory = oldConfig, oldUID, oldFactory
	})
	config.GlobalConfig = config.NewFailSafeConfig()
	firewallCleanupEffectiveUserID = func() int { return 0 }
	content, err = json.Marshal(map[string]any{"nftables": generated.entries})
	if err != nil {
		t.Fatal(err)
	}
	base := &fakeUninstallNFTRunner{}
	runner := &nftRemovalOperatorRunner{base: base, rulesets: [][]byte{content}}
	uninstallNFTRunnerFactory = func() (nftCommandRunner, error) { return runner, nil }
	if PreflightAdministratorPolicyRemoval() == nil || preflightNFTablesForUninstall(context.Background(), runner) == nil || len(base.deleteCalls) != 0 {
		t.Fatal("early or locked preflight allowed historical residue")
	}
}

func FuzzLegacyIPTablesObservation(f *testing.F) {
	f.Add([]byte(`{"nftables":[]}`), []byte("*filter\n:INPUT ACCEPT [0:0]\nCOMMIT\n"))
	f.Fuzz(func(t *testing.T, nft, save []byte) {
		_, _ = observeLegacyIPTables(nft, save)
	})
}

func TestLegacyIPTablesInputsRefuseUnboundedAndNoncanonicalValues(t *testing.T) {
	for index, inputs := range []legacyIPTablesInputs{{HAEnabled: true}, {HAEnabled: true, HAPeerPort: "062026"}, {HAPeerPort: "65536"}, {LANSubnets: []string{"192.0.2.1/24"}}, {LANSubnets: []string{"::1/128"}}, {LANSubnets: make([]string, 33)}} {
		t.Run(strconv.Itoa(index), func(t *testing.T) {
			if _, err := legacyIPTablesExpectedBlock(inputs); err == nil {
				t.Fatal("invalid generation input accepted")
			}
		})
	}
}
