//go:build linux

package firewall

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"time"
)

type legacyIPTablesObserver struct {
	nft      nftCommandRunner
	path     string
	identity nftExecutableIdentity
}

func newLegacyIPTablesObserver() (*legacyIPTablesObserver, error) {
	nft, err := newExecNFTCommandRunner()
	if err != nil {
		return nil, err
	}
	path, err := exec.LookPath("iptables-save")
	if err != nil {
		return nil, fmt.Errorf("historical iptables recovery requires its read-only save observer")
	}
	path, err = resolveLinuxWrapperExecutable(path)
	if err != nil {
		return nil, err
	}
	file, identity, err := pinNFTExecutable(path)
	if err != nil {
		return nil, err
	}
	if err := file.Close(); err != nil {
		return nil, err
	}
	return &legacyIPTablesObserver{nft: nft, path: path, identity: identity}, nil
}

// The two representations are bound by a surrounding generation fence before
// any write. argv[0] retains the explicit read-only applet name for systems
// whose iptables-save symlink targets xtables-nft-multi.
func (observer *legacyIPTablesObserver) observe(ctx context.Context) (legacyIPTablesObservation, []byte, []byte, error) {
	var empty legacyIPTablesObservation
	save, err := readLegacyIPTablesSave(ctx, observer.path, observer.identity, "nf_tables")
	if err != nil {
		return empty, nil, nil, err
	}

	nft, err := observer.nft.Run(ctx, nil, "-j", "list", "table", "ip", "filter")
	if err != nil {
		return empty, nil, nil, err
	}
	observation, err := observeLegacyIPTables(nft, save)
	return observation, nft, save, err
}

func readLegacyIPTablesSave(ctx context.Context, path string, expected nftExecutableIdentity, backend string) ([]byte, error) {
	file, identity, err := pinNFTExecutable(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()
	if identity != expected {
		return nil, fmt.Errorf("historical iptables observer changed executable identity")
	}
	child, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	command := exec.CommandContext(child, "/proc/self/fd/3", "-t", "filter")
	command.Args[0] = "iptables-save"
	command.ExtraFiles = []*os.File{file}
	command.Env = fixedLinuxWrapperCommandEnvironment()
	command.Dir = "/"
	command.WaitDelay = nftCommandProcessWait
	stdout, stderr := &boundedNFTCommandOutput{limit: 2 << 20}, &boundedNFTCommandOutput{limit: 65536}
	command.Stdout, command.Stderr = stdout, stderr
	if err := command.Run(); err != nil || child.Err() != nil || stdout.exceeded || stderr.exceeded || stderr.content.Len() != 0 {
		return nil, fmt.Errorf("historical iptables read-only observation failed; details are withheld")
	}
	save := bytes.Clone(stdout.content.Bytes())
	first, _, found := bytes.Cut(save, []byte("\n"))
	if !found || !bytes.HasPrefix(first, []byte("# Generated by iptables-save ")) || !bytes.Contains(first, []byte(" ("+backend+") ")) {
		return nil, fmt.Errorf("historical iptables read-only observation has an unexpected backend")
	}
	return save, nil
}
