name: Plumber Compliance
on:
  push:
    branches: [main]
    tags: ['v*']

# OSSF Scorecard: Enforce strict read-all at the top-level
permissions:
  contents: read

jobs:
  plumber:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write          # required to securely push Plumber Score via OIDC
      security-events: write   # required to upload SARIF to Code Scanning
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: getplumber/plumber@87ca135cc4566ba8e9065ea95b5d897232cdb208 # v0.4.16
        with:
          score-push: true
          threshold: 80
